// by Ender Smith, Editor-in-Chief, AurekFonts

const fonts = [
  {
    query: 'AncientAurebesh',
    name: 'Ancient Aurebesh',
    exampleImage: undefined,
    script: 'Domabesh',
    foundry: 'Cake',
    artistNote: '',
    description: 'Incomplete and irregular Domabesh font; probably the first Domabesh fan font ever made',
    downloadUrl: './Fonts-by-Cake/ancient-aurebesh.ttf',
    downloadType: '.TTF',
    license: 'This font is free for everyone, forever. (Copyright is under the name "shitfart", fyi)',
    licenseTag: 'Free',
    year: '2019',
    charactersImages: [],
    class: undefined,
    textSize: '1rem',
    pangram: pangrams.JediWisdom,
  },
  {
    query: 'Ataribesh',
    name: 'Ataribesh',
    exampleImage: './Ataribesh/images/Ataribesh-example-3.png',
    script: 'Aurebesh',
    foundry: 'AurekFonts',
    artistNote: '',
    description: 'An 8-bit Aurebesh font based on classic videogame fonts; 4 styles',
    downloadUrl: './Ataribesh/Ataribesh-4Pack.zip',
    downloadType: '.ZIP',
    license: 'This font is free for everyone, forever.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./Ataribesh/images/Ataribesh-charset.png', './Ataribesh/images/Ataribesh-title-charset.png', './Ataribesh/images/Ataribesh-subtitle-charset.png', './Ataribesh/images/Ataribesh-Sprites-charset.png'],
    class: 'Ataribesh',
    textSize: '1rem',
    pangram: pangrams.JediWisdom,
    additionalImages: [
      './Ataribesh/images/Ataribesh-example-2.png'
    ]
  },
  {
    query: 'Aurabesh',
    name: 'Aurabesh',
    exampleImage: undefined,
    script: 'Aurebesh',
    foundry: 'Mike E. Web',
    foundryQuery: 'MikeEWeb',
    artistNote: '',
    description: 'The first Aurebesh font; small lowercase; basic nums; non-canon punctuation & symbols',
    downloadUrl: './Aurabesh/AURABESH.ttf',
    downloadType: '.TTF',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '1996',
    charactersImages: [],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
    additionalImages: []
  },
  {
    query: 'AurebeshOcchino',
    name: 'Aurebesh (David Occhino)',
    exampleImage: undefined,
    script: 'Aurebesh',
    foundry: 'David Occhino Design',
    foundryQuery: 'DavidOcchino',
    artistNote: 'This version of the Aurebesh font has been featured in many publications, signs, posters and websites, including The Star Wars Insider Magazine, The Force.net website and Wookiepedia.',
    description: 'Aurebesh font used officially from time to time; ligature digraphs; basic nums',
    externalDownloadUrl: 'http://davidocchino.com/portfolio/typography/aurebesh.html',
    externalDownloadName: 'DavidOcchino.com',
    forLicensingName: 'DavidOcchino.com',
    forLicensingUrl: 'http://davidocchino.com/portfolio/typography/commercial-license-request-form.html',
    license: 'Single-User Non-Commercial License',
    licenseTag: 'Free NC',
    year: '1997, 2011',
    charactersImages: ['./AurebeshOcchino/AurebeshOcchino-charset.png'],
  },
  {
    query: 'AurebeshPixelSagas2000',
    name: 'Aurebesh (Pixel Sagas, 2000)',
    exampleImage: undefined,
    script: 'Aurebesh',
    foundry: 'Pixel Sagas',
    foundryQuery: 'PixelSagas',
    artistNote: '',
    description: 'Aurebesh font; capitals for digraphs; incorrect tech numerals',
    downloadUrl: './Aurebesh%20(Pixel%20Sagas%202000)/aurebesh-old.ttf',
    downloadType: '.TTF',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2000',
    charactersImages: [],
    class: 'AurebeshPixelSagas2000',
    textSize: '1rem',
    pangram: pangrams.JediWisdom,
  },
  {
    query: 'AurebeshPixelSagas',
    name: 'Aurebesh (Pixel Sagas)',
    exampleImage: undefined,
    script: 'Aurebesh',
    foundry: 'Pixel Sagas',
    foundryQuery: 'PixelSagas',
    artistNote: '',
    description: 'Popular Aurebesh font at a lighter weight; inverted capitals',
    downloadUrl: './Aurebesh%20(Pixel%20Sagas)/aurebesh.zip',
    downloadType: '.ZIP',
    license: 'Free for personal, non-commercial use.',
    licenseTag: 'Free NC',
    year: '2013',
    charactersImages: [],
    class: 'AurebeshPixelSagas',
    textSize: '1rem',
    pangram: pangrams.Podracing,
  },
  {
    query: 'AurebeshCantina',
    name: 'Aurebesh Cantina',
    exampleImage: undefined,
    script: 'Aurebesh',
    foundry: 'Pixel Sagas',
    foundryQuery: 'PixelSagas',
    artistNote: '',
    description: 'Narrow art-deco inspired Aurebesh; inverted capitals; 4 styles',
    downloadUrl: './AurebeshCantina/aurebesh_cantina.zip',
    downloadType: '.ZIP',
    license: 'Free for personal, non-commercial use.',
    licenseTag: 'Free NC',
    year: '2015',
    charactersImages: [],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'AurebeshCalligraphy',
    name: 'Aurebesh Calligraphy',
    exampleImage: './Aurebesh%20Calligraphy/AurebeshCalligraphy-example.png',
    script: 'Aurebesh',
    foundry: 'Convallarias Art',
    foundryQuery: 'ConvallariasArt',
    artistNote: '"I didn’t find any sort of things like Aurebesh cursive, so decided to do one myself c:"',
    description: 'Brush-stroke calligraphic Aurebesh font',
    downloadUrl: './Aurebesh%20Calligraphy/AurebeshCalligraphy.ttf',
    downloadType: '.TTF',
    license: 'This font is "Free for all personal and commercial use."',
    licenseTag: 'Free',
    year: '2018',
    charactersImages: ['./Aurebesh%20Calligraphy/AurebeshCalligraphy-charset.png'],
    class: 'AurebeshCalligraphy',
    textSize: '1.5rem',
    pangram: pangrams.JediWisdom,
  },
  {
    query: 'AurebeshEnglish',
    name: 'Aurebesh English',
    exampleImage: './Aurebesh%20English/aurebesh-english-example.png',
    script: 'High Galactic Alphabet',
    scriptQuery: 'HighGalactic',
    foundry: 'Stormtrooper On Weekends',
    foundryQuery: 'StormtrooperOnWeekends',
    artistNote: undefined,
    description: `High Galactic font, based on signage at Galaxy's Edge; basic nums`,
    downloadUrl: './Aurebesh%20English/Aurebesh-English.ttf',
    downloadType: '.TTF',
    license: 'This font is Free for all personal and commercial use.',
    licenseTag: 'Free',
    year: '2019',
    charactersImages: ['./Aurebesh%20English/aurebesh-english-charset.png?raw=true'],
    class: 'AurebeshEnglish',
    textSize: '2rem',
    pangram: pangrams.JediWisdom,
  },
  {
    query: 'AurebeshDroid',
    name: 'Aurebesh Droid',
    exampleImage: './Aurebesh%20Droid/aurebesh-droid-example.png',
    script: 'Droidobesh',
    foundry: 'Stormtrooper On Weekends',
    foundryQuery: 'StormtrooperOnWeekends',
    artistNote: '"This font is based on the droid version of the Aurebesh typeface used in Star Wars."',
    description: 'Basic Droidobesh font; tech nums',
    downloadUrl: './Aurebesh%20Droid/Aurebesh-Droid.ttf',
    downloadType: '.TTF',
    license: 'This font is Free for all personal and commercial use.',
    licenseTag: 'Free',
    year: '2019',
    charactersImages: ['./Aurebesh%20Droid/aurebesh-droid-charset.png?raw=true'],
    class: 'AurebeshDroid',
    textSize: '2rem',
    pangram: pangrams.JediWisdom,
  },
  {
    query: 'AurebeshNewRoman',
    name: 'Aurebesh New Roman',
    exampleImage: undefined,
    script: 'Aurebesh',
    foundry: 'David Occhino Design',
    foundryQuery: 'DavidOcchino',
    artistNote: '"AUREBESH NEW ROMAN is a serif-style typeface inspired by the Star Wars "Aurebesh" alphabet. Created to fill a need for a more legible Aurebesh typeface, Aurebesh New Roman can be used to set larger passages of text."',
    description: 'Serif Aurebesh font; basic nums; ligature digraphs; 6 styles',
    externalDownloadUrl: 'http://davidocchino.com/portfolio/typography/aurebesh-new-roman.html',
    externalDownloadName: 'DavidOcchino.com',
    forLicensingName: 'DavidOcchino.com',
    forLicensingUrl: 'http://davidocchino.com/portfolio/typography/commercial-license-request-form.html',
    license: 'Single-User Non-Commercial License',
    licenseTag: 'Free NC',
    year: '2014',
    charactersImages: ['./AurebeshNewRoman/Aurebesh-New-Roman-charset.png'],
  },
  {
    query: 'AurebeshOmaTres',
    name: 'Aurebesh Oma Tres',
    exampleImage: './AurebeshOmaTres/Aurebesh_OmaTres-example.png',
    script: 'Aurebesh',
    foundry: 'AurekFonts',
    artistNote: '',
    description: 'Aurebesh font based on the Star Wars logo and named for Oma Tres from The Rise of Skywalker',
    downloadUrl: './AurebeshOmaTres/Aurebesh_OmaTres_beta.otf',
    downloadType: '.OTF',
    license: 'This font is free for everyone, forever.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./AurebeshOmaTres/Aurebesh_OmaTres-charset.png'],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'AurebeshPixel',
    name: 'Aurebesh Pixel',
    exampleImage: './AurebeshPixel/Aurebesh-Pixel-example.png',
    script: 'Aurebesh',
    foundry: 'AurekFonts',
    artistNote: '',
    description: 'Pixel Aurebesh font; basic nums',
    downloadUrl: './AurebeshPixel/aurebesh-pixel.zip',
    downloadType: '.ZIP',
    license: 'This font is free for everyone, forever.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./AurebeshPixel/Aurebesh-Pixel-characters2.png'],
  },
  {
    query: 'AurebeshRodian',
    name: 'Aurebesh Rodian',
    exampleImage: './Aurebesh%20Rodian/Aurebesh_Rodian-oblique-outline-example.png',
    script: 'Aurebesh',
    foundry: 'AurekFonts',
    artistNote: '',
    description: 'A curvy and friendly Aurebesh font; 4 styles',
    downloadUrl: './Aurebesh%20Rodian/Aurebesh_Rodian.zip',
    downloadType: '.ZIP',
    license: 'This font is free for everyone, forever.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./Aurebesh%20Rodian/Aurebesh_Rodian-charset.png'],
    class: 'AurebeshRodian',
    textSize: '1.5rem',
    pangram: pangrams.JediWisdom,
  },
  {
    query: 'AurebeshTycho',
    name: 'Aurebesh Tycho',
    exampleImage: undefined,
    script: 'Aurebesh',
    foundry: 'Tycho Ordo',
    foundryQuery: 'TychoOrdo',
    artistNote: '',
    description: 'A robust Aurebesh font; ligature-digraphs; optional inverted capitals and tech numerals',
    downloadUrl: './Aurebesh%20(Tycho%20Ordo)/AurebeshTycho.zip',
    downloadType: '.ZIP',
    license: 'Free for personal, non-commercial use.',
    licenseTag: 'Free NC',
    year: '2012, 2015, 2020',
    charactersImages: [],
    class: 'AurebeshTycho',
    textSize: '1.5rem',
    pangram: pangrams.BlackholeDigraphs,
  },
  {
    query: 'AurebeshSheev',
    name: 'Aurebesh Sheev',
    exampleImage:  `./AurebeshSheev/AurebeshSheev-example.png`,
    script: 'Aurebesh',
    foundry: 'AurekFonts',
    artistNote: '',
    description: 'Elegant hand-written Aurebesh font; still in beta; tech nums; 3 styles',
    downloadUrl: './AurebeshSheev/AurebeshSheev-BETA.zip',
    downloadType: '.ZIP',
    license: 'This font is free for everyone, forever.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./AurebeshSheev/AurebeshSheev-charset.png'],
    class: undefined,
    textSize: '1.5rem',
    pangram: pangrams.JediWisdom,
  },
  {
    query: 'AurebeshTypewriter',
    name: 'Aurebesh Typewriter',
    exampleImage:  `./AurebeshTypewriter/AurebeshTypewriter-example.png`,
    script: 'Aurebesh',
    foundry: 'AurekFonts',
    artistNote: '',
    description: 'Type-written Aurebesh font in two weights; digraphs mapped to symbol keys; basic nums',
    downloadUrl: './AurebeshTypewriter/AurebeshTypewriter.zip',
    downloadType: '.ZIP',
    license: 'This font is free for everyone, forever.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./AurebeshTypewriter/AurebeshTypewriter-charset.png'],
    class: undefined,
    textSize: '1.5rem',
    pangram: pangrams.JediWisdom,
  },
  {
    query: 'AurekBesh',
    name: 'Aurek-Besh',
    exampleImage: './AurekBesh/aureclip.jpg',
    script: 'Aurebesh',
    foundry: 'Boba Fonts',
    foundryQuery: 'BobaFonts',
    seeAlso: `Aurek-Besh Hand`, 
    seeAlsoQuery: `AurekBeshHand`,
    artistNote: 'Feel free to distribute the zip but remember to keep it intact and complete. This font is freeware.',
    description: `Standard Aurebesh font; tech nums; 2 styles`,
    downloadUrl: './AurekBesh/boba-fonts_aurek-besh.zip',
    downloadType: '.ZIP',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '1999',
    charactersImages: ['./AurekBesh/aurek-besh-charset.png'],
  },
  {
    query: 'AurekBeshHand',
    name: 'Aurek-Besh Hand',
    exampleImage: './AurekBeshHand/aurek-besh-hand-example.png',
    script: 'Aurebesh',
    foundry: 'Boba Fonts',
    foundryQuery: 'BobaFonts',
    seeAlso: `Aurek-Besh`, 
    seeAlsoQuery: `AurekBesh`, 
    artistNote: 'Feel free to distribute the zip but remember to keep it intact and complete. This font is freeware.',
    description: `Handwritten Aurebesh font; tech nums`,
    downloadUrl: './AurekBeshHand/boba-fonts_aurek-besh-hand.zip',
    downloadType: '.ZIP',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '1999',
    charactersImages: ['./AurekBeshHand/aurek-besh-hand-charset.png'],
    // class: 'AurekBeshHand', // TODO: Fix this?
    textSize: '2rem',
    pangram: pangrams.Podracing,
  },
  {
    query: 'AurekbeshMicalHandwritten',
    name: 'Aurekbesh Mical Handwritten',
    exampleImage: './AurekbeshMicalHandwritten/AurekbeshMicalHandwritten-example.png',
    script: 'Aurebesh',
    foundry: 'Kopanitsak',
    foundryQuery: 'Kopanitsak',
    artistNote: `"!!!Please don't offer this download anywhere else!!!"`,
    description: `Handwritten Aurebesh font; tech nums`,
    externalDownloadUrl: 'https://www.deviantart.com/download/144424955/d2dzj0b-ab1b618e-9c8d-470f-9d4c-57c938815660.7z?token=f0eb954c663f2e77df03e90887860d57dc71ed42&ts=1589972369',
    externalDownloadName: 'deviantart',
    license: 
      `<a 
        href="http://creativecommons.org/licenses/by-nc-nd/3.0/"
      >
        Creative Commons Attribution-Noncommercial-No Derivative Works 3.0 License
      </a>`,
    licenseTag: 'Free NC',
    year: '2009',
    charactersImages: ['./AurekbeshMicalHandwritten/AurekbeshMicalHandwritten-charset.png'],
    class: undefined, 
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'Boonta',
    name: `Boonta`,
    exampleImage: './banners/unknown-scripts.png',
    script: `Unidentified podracer-detail`,
    scriptQuery: `UnknownCanon`,
    foundry: 'Omega Design',
    foundryQuery: 'OmegaDesign',
    artistNote: ``,
    description: `Font based on unidentified markings on one or more podracers in The Phantom Menace`,
    downloadUrl: './Boonta/Boonta.zip',
    downloadType: '.ZIP',
    license: 'These fonts are "Charity-ware". (Meaning: if you like the fonts and plan to use them, please give a little more than usual to your favorite charities [...] or others the next time you have a chance.)',
    licenseTag: 'Free',
    year: '1999',
    charactersImages: [],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'ClyneseBend',
    name: 'Clynese Bend',
    exampleImage: `./ClyneseBend/Clynese_Bend-example.png`,
    script: 'Clynese / Corellian',
    scriptQuery: 'Clynese',
    foundry: 'AurekFonts',
    seeAlso: `Clynese Hand`, 
    seeAlsoQuery: `ClyneseHand`, 
    artistNote: '',
    description: 'Clynese variant for streetsigns; letter y is upside down; non-canon nums, based on Sabacc dice and cards',
    downloadUrl: './ClyneseBend/Clynese_Bend.otf',
    downloadType: '.OTF',
    license: 'This font is free for everyone, forever.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./ClyneseBend/Clynese_Bend-charset1.png'],
  },
  {
    query: 'ClyneseHand',
    name: 'Clynese Hand',
    exampleImage: `./ClyneseHand/Clynese_Hand-example.png`,
    script: 'Clynese / Corellian',
    scriptQuery: 'Clynese',
    foundry: 'AurekFonts',
    seeAlso: `Clynese Bend`, 
    seeAlsoQuery: `ClyneseBend`, 
    artistNote: '',
    description: 'Hand-written clynese font; case controls placement; non-canon nums, based on Sabacc dice and cards',
    downloadUrl: './ClyneseHand/Clynese_Hand.otf',
    downloadType: '.OTF',
    license: 'This font is free for everyone, forever.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./ClyneseHand/Clynese_Hand-charset.png'],
  },
  {
    query: 'DarkKatarn',
    name: 'Dark Katarn',
    exampleImage: './DarkKatarn/drkkatrn_sample.gif',
    script: 'Atrisian',
    foundry: 'erikstormtrooper',
    artistNote: `"ACCURACY OF THIS FONT There are only 12 "canon" letters in this alphabet, which appear in X-Wing. In my font, these letters are represented as: A, C, D, E, H, I, L, N, O, R, S, T. These 12 letters are the most frequent in English. I chose them so written passages would look as canon as possible. Most of the other letters in this font were inspired by barely-legible characters seen in Dark Forces. Numbers 1-6 are canon based on numbers seen in Dark Forces. I created numbers 7-9 and 0 in the same style."`,
    description: `<em>(Legends)</em> First fan font for Atrisian`,
    downloadUrl: './DarkKatarn/drkkatrn.zip',
    downloadType: '.ZIP',
    license: 'This font is freeware; it may be distributed freely, but PLEASE distribute all files included in the ZIP archive. This font is NOT to be sold  or used for financial gain. Help keep it free and available!',
    licenseTag: 'Free NC',
    year: '2003, 2004',
    charactersImages: [],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'DockingBay94',
    name: 'Docking Bay 94',
    exampleImage: `./DockingBay94/DockingBay94-example.png`,
    script: 'Aurebesh',
    foundry: 'AurekFonts',
    artistNote: '',
    description: 'Aurebesh font based on the docking bay signage at Mos Eisley Spaceport (Star Wars the Motion Picture, and The Mandalorian S1)',
    downloadUrl: './DockingBay94/DockingBay94-Display.otf',
    downloadType: '.OTF',
    license: 'This font is free for everyone, forever.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./DockingBay94/DockingBay94-charset.png'],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'DomabeshConsole',
    name: 'Domabesh Console',
    exampleImage: `./banners/domabesh-banner.png`,
    script: 'Domabesh',
    foundry: 'AurekFonts',
    artistNote: 'All the letters but J and V are canonical. The numbers and punctuation are noncanonical',
    description: 'Basic Domabesh font; digraphs mapped to symbol keys; tech nums',
    downloadUrl: './Domabesh_Console/DomabeshConsole.otf',
    downloadType: '.OTF',
    license: 'This font is free for everyone, forever.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./Domabesh_Console/DomabeshConsole-charset.png'],
    class: 'DomabeshConsole',
    textSize: '2rem',
    pangram: pangrams.short,
  },
  {
    query: 'Ewok',
    name: 'Ewok',
    exampleImage: undefined,
    script: 'Ewokese',
    foundry: 'Omega Design',
    foundryQuery: 'OmegaDesign',
    artistNote: '"Characters do *not* represent the keys they they are on.  Each character seems to stand for a word or situation. Ewok is written downward, not left to right."',
    description: '<em>Legends</em> Ewokese font based on symbols in the cartoon series.',
    downloadUrl: './Ewok/Ewok.zip',
    downloadType: '.ZIP',
    license: 'These fonts are "Charity-ware". (Meaning: if you like the fonts and plan to use them, please give a little more than usual to your favorite charities [...] or others the next time you have a chance.)',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: [],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'GalacticBasic',
    name: 'Galactic Basic',
    exampleImage: `./GalacticBasic/GalacticBasic-example.png`,
    script: '"Imperial Code"',
    scriptQuery: 'ImperialCode',
    foundry: 'erikstormtrooper',
    artistNote: '',
    description: `"Imperial Code" font based on designs by Joe Johnston for Return of the Jedi and Philip Metschan for Attack of the Clones`,
    downloadUrl: './GalacticBasic/galactic_basic.zip',
    downloadType: '.ZIP',
    license: 'This font is freeware; it may be distributed freely, but PLEASE distribute all files included in the ZIP archive. This font is NOT to be sold  or used for financial gain. Help keep it free and available!',
    licenseTag: 'Free NC',
    year: '1996, 2002',
    charactersImages: ['./GalacticBasic/GalacticBasic-charset.png'],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'GeonosianPM',
    name: 'Geonosian PM',
    exampleImage: `./Geonosian%20PM/GeonosianPM-example.png`,
    script: 'Geonosian',
    foundry: 'AurekFonts',
    artistNote: '',
    description: `Geonosian font based on Philip Metschan's original design`,
    downloadUrl: './Geonosian%20PM/GeonosianPM.otf',
    downloadType: '.OTF',
    license: 'This font is free for everyone, forever.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./Geonosian%20PM/GeonosianPM-charset.png'],
    class: 'GeonosianPM',
    textSize: '2rem',
    pangram: pangrams.Podracing,
  },
  {
    query: 'Kitisakkullian',
    name: 'Kitisakkullian',
    exampleImage: './Kitisakkullian/Kitisakkullian-example.png',
    script: 'Kitisakkullian',
    foundry: 'AurekFonts',
    artistNote: ``,
    description: `Kitisakkullian font; all glyphs are canon; their mapping is arbitrary`,
    downloadUrl: './Kitisakkullian/Kitisakkullian.otf',
    downloadType: '.OTF',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./Kitisakkullian/Kitisakkullian-charset.png'],
    textSize: '2rem',
    pangram: pangrams.short,
  },
  {
    query: 'KCDAurebesh',
    name: 'Kyber Crystal Display Aurebesh',
    exampleImage: './Kyber%20Crystal%20Display/KCD-example.png',
    script: 'Aurebesh',
    foundry: 'AurekFonts',
    artistNote: ``,
    description: `For security consoles; includes Alphabet version`,
    seeAlso: `Kyber Crystal Display Alphabet`, 
    seeAlsoQuery: `KCDAlphabet`, 
    downloadUrl: './Kyber%20Crystal%20Display/KyberCrystalDisplay.zip',
    downloadType: '.ZIP',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./Kyber%20Crystal%20Display/KCD-Aurebesh-charset.png'],
    textSize: '2rem',
    pangram: pangrams.short,
  },
  {
    query: 'KCDAlphabet',
    name: 'Kyber Crystal Display Alphabet',
    exampleImage: './Kyber%20Crystal%20Display/KCD-example.png',
    script: 'HighGalactic',
    foundry: 'AurekFonts',
    artistNote: ``,
    description: `For security consoles; includes Aurebesh version`,
    seeAlso: `Kyber Crystal Display Aurebesh`, 
    seeAlsoQuery: `KCDAurebesh`, 
    downloadUrl: './Kyber%20Crystal%20Display/KyberCrystalDisplay.zip',
    downloadType: '.ZIP',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./Kyber%20Crystal%20Display/KCD-Alphabet-charset.png'],
    textSize: '2rem',
    pangram: pangrams.short,
  },
  {
    query: 'LizzieUniverseAurebesh',
    name: 'Lizzie Universe Aurebesh',
    exampleImage: './LizzieUniverseAurebesh/LizzieUniverseAurebesh-example.png',
    script: 'Aurebesh',
    foundry: 'Lizzie Universe',
    foundryQuery: 'LizzieUniverse',
    artistNote: ``,
    description: `8-bit Aurebesh font A-Z`,
    downloadUrl: './LizzieUniverseAurebesh/LizzieUniverseAurebesh.zip',
    downloadType: '.ZIP',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./LizzieUniverseAurebesh/LizzieUniverseAurebesh-charset.png'],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'Maulobesh',
    name: 'Maulobesh',
    exampleImage: './Maulobesh/Maulobesh-example-1.png',
    script: 'Aurebesh',
    foundry: 'AurekFonts',
    artistNote: ``,
    description: `A blackletter Aurebesh font; tech nums; basic punctuation`,
    downloadUrl: './Maulobesh/Maulobesh.otf',
    downloadType: '.OTF',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./Maulobesh/Maulobesh-charset.png'],
    class: 'Maulobesh',
    textSize: '2rem',
    pangram: pangrams.short,
  },
  {
    query: 'Mandalorian',
    name: 'Mandalorian',
    exampleImage: './Mandalorian/mandalorian_sample.gif',
    script: 'Mandalorian',
    foundry: 'erikstormtrooper',
    artistNote: ``,
    description: `Mandalorian font based on Philip Metschan's design seen in the Slave I's consoles in Attack of the Clones; a few letters off-canon; Mandalorian nums`,
    downloadUrl: './Mandalorian/mandalor.zip',
    downloadType: '.ZIP',
    license: 'This font is freeware; it may be distributed freely, but PLEASE distribute all files included in the ZIP archive. This font is NOT to be sold  or used for financial gain. Help keep it free and available!',
    licenseTag: 'Free NC',
    year: '2005, 2010',
    charactersImages: ['./Mandalorian/mandalorian-charset.png'],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'AlbansBane',
    name: `Mando Alban's Bane`,
    exampleImage: './MandoAlbansBane/Mando_AlbansBane-example.png',
    script: `Mandalorian`,
    foundry: 'AurekFonts',
    artistNote: ``,
    description: `Mandalorian font based on the Visual Encyclopedia; missing punctuation; Mandalorian nums`,
    downloadUrl: './MandoAlbansBane/Mando_AlbansBaneBETA.otf',
    downloadType: '.OTF',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./MandoAlbansBane/Mando_AlbansBane-charset.png'],
    class: 'MandoAlbansBane',
    textSize: '3rem',
    pangram: 'This is the way',
  },
  {
    query: 'MetalRebel',
    name: 'Metal Rebel',
    exampleImage: './MetalRebel/metalrebel_sample.gif',
    script: 'UnknownCanon',
    foundry: 'erikstormtrooper',
    artistNote: `"FONT INFORMATION This Star Wars font was inspired by writing on two Y-Wing helmets worn by Grey Squadron in Return of the Jedi. This font includes all English letters, numbers, and common punctuation marks (basically, all the stuff displayed on the keyboard). Uppercase and lowercase  letters are identical except that uppercase letters have a slightly taller spine. Also, kerning has been enabled for this font. <br /> ACCURACY OF THIS FONT There are only 11 "canon" letters in this alphabet, taken from two Y-Wing helmets in ROJ. These 11 canon letters are represented as:  A, D, E, H, I, L, N, O, R, S, T. These are the 11 most frequently  used letters in English. I chose them so that written passages  would look as canon as possible. I modeled the other letters in  this font to match the "square-ness" of the canon letters, which  bear a faint resemblance to a sans-serifed Hebrew.  The concept for numbers comes from one of the markings on the side of Grey Leader's helmet. Since I had a kind of Hebrew theme going,  I also used that as an inspiration for the numbers. Modern Hebrew  commonly uses arabic numerals (1-9), but in ancient Hebrew, letters  of the alphabet got double-duty as numbers. So, I based numbers  1-9 (and 0) on the first 10 letters of this font."`,
    description: `Unidentified script font based upon Grey Leader's helmet in Return of the Jedi`,
    downloadUrl: './MetalRebel/metlrebl.zip',
    downloadType: '.ZIP',
    license: 'This font is freeware; it may be distributed freely, but PLEASE distribute all files included in the ZIP archive. This font is NOT to be sold  or used for financial gain. Help keep it free and available!',
    licenseTag: 'Free NC',
    year: '2004',
    charactersImages: ['./MetalRebel/Metal-Rebel-charset.png'],
    additionalImages: ['./MetalRebel/Metal-Rebel-example.png'],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'Naboo',
    name: `Naboo`,
    exampleImage: undefined,
    script: `Naboo Futhark`,
    scriptQuery: `NabooFuthark`,
    foundry: 'Omega Design',
    foundryQuery: 'OmegaDesign',
    artistNote: ``,
    description: `Futhark font based on the markings on Naboo Starfighters in the Phantom Menace`,
    downloadUrl: './Naboo/Naboo.zip',
    downloadType: '.ZIP',
    license: 'These fonts are "Charity-ware". (Meaning: if you like the fonts and plan to use them, please give a little more than usual to your favorite charities [...] or others the next time you have a chance.)',
    licenseTag: 'Free',
    year: '1999',
    charactersImages: [],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'NalHuttese',
    name: `Nal-Huttese`,
    exampleImage: undefined,
    script: `Outer Rim Basic`,
    scriptQuery: `OuterRim`,
    foundry: 'Omega Design',
    foundryQuery: 'OmegaDesign',
    artistNote: `The most common version of this font you will find was made in 1999 and contains numerals 1-3 and the letters A-T. Harder to find is a 2000 version with 0-9 and A-Z. This download contains both, with the 1999 one marked as Nal-Huttese-99. It is included only for historical purposes, don't install it.`,
    description: `Outer Rim Basic font misidentified as Huttese, based on glyphs seen in The Phantom Menace; 2 versions included`,
    downloadUrl: './NalHuttese/nal-hutt.zip',
    downloadType: '.ZIP',
    license: 'These fonts are "Charity-ware". (Meaning: if you like the fonts and plan to use them, please give a little more than usual to your favorite charities [...] or others the next time you have a chance.)',
    licenseTag: 'Free',
    year: '1999, 2000',
    charactersImages: [],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'NewAurabesh',
    name: `New Aurabesh`,
    exampleImage: './NewAurabesh/NewAurabesh-example.png',
    script: `Aurebesh`,
    scriptQuery: `Aurebesh`,
    foundry: 'Peter Schuster',
    foundryQuery: 'PeterSchuster',
    artistNote: `About: <a href="https://www.ko-fi.com/post/New-Aurabesh-A-Casual-Interview-with-Peter-Schu-Q5Q41QAX6">Aurabesh New: A Casual Interview with Peter Schuster</a>`,
    description: `Standard Aurebesh font; small tech nums`,
    downloadUrl: './NewAurebesh/newaure.zip',
    downloadType: '.ZIP',
    license: 'Free for all personal and commercial uses',
    licenseTag: 'Free',
    year: '1998',
    charactersImages: [],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'NewFuthork',
    name: 'New Futhork',
    exampleImage: './NewFuthork/newfuthork_sample.gif',
    script: 'NabooFuthork',
    foundry: 'erikstormtrooper',
    artistNote: `"FONT INFORMATION This font is a canon version of the Star Wars alphabet known as "Naboo Futhork". The details of this font were taken from the passcodes screen in the 2000 game "Battle For Naboo". "`,
    description: `Naboo Futhork font; no nums`,
    downloadUrl: './NewFuthork/new_futhork.zip',
    downloadType: '.ZIP',
    license: 'This font is freeware; it may be distributed freely, but PLEASE distribute all files included in the ZIP archive. This font is NOT to be sold  or used for financial gain. Help keep it free and available!',
    licenseTag: 'Free NC',
    year: '2006, 2008',
    charactersImages: ['./NewFuthork/newfuthork_table.jpg'],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'Nirvanabesh',
    name: 'Nirvanabesh',
    exampleImage: './Nirvanabesh/Nirvanabesh-example.png',
    script: 'Aurebesh',
    foundry: 'Vamplify',
    artistNote: `(with kerning by <a href="${pathname}?foundry=AurekFonts">AurekFonts</a>).`,
    description: `A serif Aurebesh font based on the band Nirvana's logotype; no nums; no symbols`,
    downloadUrl: './Nirvanabesh/Nirvanabesh.otf',
    downloadType: '.OTF',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./Nirvanabesh/Nirvanabesh-charset.png'],
    class: 'Nirvanabesh',
    textSize: '5rem',
    pangram: pangrams.short,
  },
  {
    query: 'OldTongue',
    name: 'Old Tongue',
    exampleImage: undefined,
    script: '"The Old Tongue" / Ur-Kittât',
    scriptQuery: 'OldTongue',
    foundry: 'Cake',
    artistNote: ``,
    description: `Slightly pixelated Old Tongue font; probably the first fan-made Old Tongue font`,
    downloadUrl: './Fonts-by-Cake/old-tongue.ttf',
    downloadType: '.TTF',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2019',
    charactersImages: [],
    class: undefined,
    textSize: '2rem',
    pangram: pangrams.short,
  },
  {
    query: 'OldTongueYavin',
    name: 'Old Tongue Yavin',
    exampleImage: './Old%20Tongue%20Yavin/OldTongue_Yavin-example.png',
    script: '"The Old Tongue" / Ur-Kittât',
    scriptQuery: 'OldTongue',
    foundry: 'AurekFonts',
    artistNote: ``,
    description: `Basic Old Tongue font; non-canon punctuation; non-canon tech nums; letter U is a little off`,
    downloadUrl: './Old%20Tongue%20Yavin/OldTongue_Yavin.otf',
    downloadType: '.OTF',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./Old%20Tongue%20Yavin/OldTongue_Yavin-charset.png'],
    class: 'OldTongueYavin',
    textSize: '3rem',
    pangram: pangrams.short,
  },
  {
    query: 'OuterRimDisplay',
    name: 'Outer Rim Display',
    exampleImage: './OuterRimDisplay/OuterRimDisplay_BETA-example.png',
    script: 'Outer Rim Basic',
    scriptQuery: 'OuterRim',
    foundry: 'AurekFonts',
    artistNote: ``,
    description: `Outer Rim Basic font based on the one used in The Clone Wars series; no nums; no symbols`,
    downloadUrl: './OuterRimDisplay/OuterRimDisplay_BETA.otf',
    downloadType: '.OTF',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./OuterRimDisplay/OuterRimDisplay_BETA-charset.png'],
    class: 'OuterRimDisplay',
    textSize: '3rem',
    pangram: pangrams.short,
  },
  {
    query: 'Protobesh',
    name: 'Protobesh',
    exampleImage: './Protobesh/protobesh-example.png',
    script: 'Protobesh / Coremaic',
    scriptQuery: 'Protobesh',
    foundry: 'AurekFonts',
    artistNote: `"It was a long process to decode this script from the artwork for The Rise of Skywalker, but it holds up to scrutiny."`,
    description: `Protobesh font based on inscriptions in the Sacred Jedi Texts; non-canon nums; 2 styles`,
    downloadUrl: './Protobesh/Protobesh.zip',
    downloadType: '.ZIP',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./Protobesh/ProtobeshCoremaic-charset.png', './Protobesh/ProtobeshSquare-charset.png'],
    class: 'ProtobeshCoremaic',
    textSize: '3rem',
    pangram: pangrams.short,
  },
  {
    query: 'SaculBasic',
    name: 'Sacul Basic',
    exampleImage: './Sacul/SaculBasic-example.jpg',
    script: 'Aurebesh',
    scriptQuery: 'Aurebesh',
    foundry: 'Louie Mantia, Jr.',
    foundryQuery: 'LouieMantia',
    seeAlso: 'Sacul High Alphabet',
    seeAlsoQuery: 'SaculHighAlphabet',
    artistNote: `"This type is inspired by the designs seen in Star Wars. It isn't a replica of type seen in the films. Instead, it's a reinterpretation of existing characters to be a more legible, cohesive alphabet. Included is a Latin alphabet version as well, inspired by type seen in the Tokyo Disneyland Star Tours queue."`,
    description: `Aurebesh font redesined for clarity and balance; basic nums; comes with High Galactic version`,
    externalDownloadUrl: 'https://gumroad.com/l/sacul',
    externalDownloadName: `Louie Mantia's gumroad`,
    license: 'The font is only for personal, non-commercial use. If you wish to use this font commercially, you must first purchase a commercial license.',
    licenseTag: 'Lic Req',
    year: '2020',
    charactersImages: ['./Sacul/SaculBasic-charset.jpg'],
    additionalImages: ['./AurekFontsBanner.png'],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'SaculHighAlphabet',
    name: 'Sacul High Alphabet',
    exampleImage: './Sacul/SaculHighAlphabet-example.jpg',
    script: 'High Galactic Alphabet',
    scriptQuery: 'HighGalactic',
    foundry: 'Louie Mantia, Jr.',
    foundryQuery: 'LouieMantia',
    seeAlso: 'Sacul High Alphabet',
    seeAlsoQuery: 'SaculHighAlphabet',
    artistNote: `"Inspired by type seen in the Tokyo Disneyland Star Tours queue."`,
    description: `High Galactic font inspired by text in the Tokyo Disneyland Star Tours queue; comes with Aurebesh version`,
    externalDownloadUrl: 'https://gumroad.com/l/sacul',
    externalDownloadName: `Louie Mantia's gumroad`,
    license: 'The font is only for personal, non-commercial use. If you wish to use this font commercially, you must first purchase a commercial license.',
    licenseTag: 'Lic Req',
    year: '2020',
    charactersImages: ['./Sacul/SaculHighAlphabet-charset.jpg'],
    additionalImages: [],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'SithProphecy',
    name: 'Sith Prophecy',
    exampleImage: './SithProphecy/sithprophecy_sample.gif',
    script: 'Unidentified script',
    scriptQuery: 'UnknownCanon',
    foundry: 'erikstormtrooper',
    artistNote: ``,
    description: `Font based on the unidentified writing on every known version of Darth Vader's chestbox`,
    downloadUrl: './SithProphecy/sthproph.zip',
    downloadType: '.ZIP',
    license: 'This font is freeware; it may be distributed freely, but PLEASE distribute all files included in the ZIP archive. This font is NOT to be sold  or used for financial gain. Help keep it free and available!',
    licenseTag: 'Free NC',
    year: '2004, 2006',
    charactersImages: ['./SithProphecy/sithprophecy_table.jpg', './SithProphecy/sithprophecy_guide.gif'],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'SWyavin4',
    name: 'SWyavin4',
    exampleImage: undefined,
    script: 'Quasi-Old Tongue',
    scriptQuery: 'OldTongue',
    foundry: `\"Tommy\" of Escondido`,
    foundryQuery: `TommyofEscondido`,
    artistNote: `"This is the Yavin 4 font, based on the Alien lettering used in THE ILLUSTRATED STARWARS UNIVERSE book on the Yavin 4 temple walls.  This was an illustration of the movie: StarWars: A New Hope. The jungle temple on the Yavin 4 moon was  the final base from which the rebels attacked the first Death Star.  The script is also known as Teresian, according to the StarWars comic books.  It seems to  be written horizontal, but it is uncertain if it is right-to-left or vice-versa."`,
    description: `Non-canon glyphs, based on the same source material as the "Old Tongue" proper`,
    downloadUrl: './SWyavin4/swyavin4.zio',
    downloadType: '.ZIP',
    license: 'This is charity-ware - if you find it at all worthwhile, please give more to charity',
    licenseTag: 'Free',
    year: '1997',
    charactersImages: [],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'TradeHuttese',
    name: 'Trade Huttese',
    exampleImage: undefined,
    script: `"Jabba's Alphabet" <em>(Legends)</em>`,
    scriptQuery: 'JabbasAlphabet',
    foundry: `\"Tommy\" of Escondido`,
    foundryQuery: `TommyofEscondido`,
    artistNote: ``,
    description: `<em>Legends</em> font based on "Jabba's Alphabet" from 1997 Pizza Hut boxes`,
    downloadUrl: './TradeHuttese/huttese.zip',
    downloadType: '.ZIP',
    license: `This is charity-ware - if you find it at all worthwhile, please give more to charity`,
    licenseTag: 'Free',
    year: '1999',
    charactersImages: [],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'TradeFederation',
    name: 'Trade Federation',
    exampleImage: undefined,
    script: `Trade Federation Basic`,
    scriptQuery: 'TradeFederation',
    foundry: `Peter Schuster`,
    foundryQuery: `PeterSchuster`,
    artistNote: ``,
    description: `Trade Federation font, based on pre-release information for The Phantom Menace from StarWars.com; A-Z, 1-6; Trade Federation nums`,
    downloadUrl: './TradeFederation/tradefederation.zip',
    downloadType: '.ZIP',
    license: `Free Personal Non-Commercial`,
    licenseTag: 'Free NC',
    year: '1998',
    charactersImages: [],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'UbeseBoushh',
    name: 'Ubese Boushh',
    exampleImage: './Ubese%20Boushh%20BETA/Ubese_Boushh_BETA-example.png',
    script: `\'Ubese\' [unidentified script from Boushh's costume]`,
    scriptQuery: 'Ubese',
    foundry: 'AurekFonts',
    artistNote: `"There are only enough letters to fill out the phonology of Ubese, as heard in RotJ."`,
    description: `"Ubese" font based on Boushh's clothing; limited glyphs; some non-canon glyphs; no nums`,
    downloadUrl: './Ubese%20Boushh%20BETA/ubese-boushh-beta.zip',
    downloadType: '.ZIP',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./Ubese%20Boushh%20BETA/Ubese_Boushh_BETA-charaset.png'],
    class: undefined,
    textSize: '3rem',
    pangram: pangrams.short,
  },

]