// by Ender Smith, Editor-in-Chief, AurekFonts

const fonts = [
  {
    query: 'AlmostThere',
    name: 'Almost There',
    exampleImage: './AlmostThere/almostthere-example-1.png',
    script: 'Numeric',
    foundry: 'AurekFonts',
    artistNote: '',
    description: 'Numeric font based on the x-wing targeting computer',
    downloadUrl: './AlmostThere/AlmostThere-Numeric.otf',
    downloadType: '.OTF',
    license: 'Free for everyone forever',
    licenseTag: 'Free',
    year: '2019',
    charactersImages: ['./AlmostThere/almostthere-example-4.png'],
    additionalImages: [
      './AlmostThere/almostthere-example-2.png',
      './AlmostThere/almostthere-example-3.png',
    ],
    class: 'almostthere-text almostthere-demo',
    textSize: '3rem',
    pangram: '0546372819',
  },
  {
    query: 'AncientAurebesh',
    name: 'Ancient Aurebesh',
    exampleImage: undefined,
    script: 'Domabesh',
    foundry: 'Cake',
    artistNote: '',
    description: 'Incomplete and irregular Domabesh font; probably the first Domabesh fan font ever made',
    downloadUrl: './FontsByCake/ancient-aurebesh.ttf',
    downloadType: '.TTF',
    license: 'This font is free for everyone, forever. (Copyright is under the name "shitfart", fyi)',
    licenseTag: 'Free',
    year: '2019',
    charactersImages: [],
    class: 'ancientaurebesh-text domabeshconsole-demo',
    textSize: '3.5rem',
    pangram: pangrams.Jedha,
  },
  {
    query: 'Ataribesh',
    name: 'Ataribesh',
    exampleImage: './Ataribesh/images/Ataribesh-example-3.png',
    script: 'Aurebesh',
    foundry: 'AurekFonts',
    artistNote: '',
    description: 'An 8-bit Aurebesh font based on classic videogame fonts; 4 styles',
    downloadUrl: './Ataribesh/Ataribesh-4Pack.zip',
    downloadType: '.ZIP',
    license: 'This font is free for everyone, forever.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./Ataribesh/images/Ataribesh-charset.png', './Ataribesh/images/Ataribesh-title-charset.png', './Ataribesh/images/Ataribesh-subtitle-charset.png', './Ataribesh/images/Ataribesh-Sprites-charset.png'],
    class: 'Ataribesh ataribesh-demo',
    textSize: '2rem',
    pangram: 'game over',
    additionalImages: [
      './Ataribesh/images/Ataribesh-example-2.png'
    ]
  },
  {
    query: 'AttackPosition',
    name: 'Attack Position',
    exampleImage: './AttackPosition/AttackPosition-example.png',
    script: 'Symbolic',
    foundry: 'AurekFonts',
    artistNote: '',
    description: 'Symbolic font based on console buttons from <em>Star Wars</em>, <em>Rogue One</em>, and <em>Solo</em>.',
    downloadUrl: './AttackPosition/AttackPosition.zip',
    downloadType: '.ZIP',
    license: 'Free for everyone forever',
    licenseTag: 'Free',
    year: '2019',
    charactersImages: ['./AttackPosition/AttackPosition-charset.png'],
    textSize: '3rem',
  },
  {
    query: 'Aurabesh',
    name: 'Aurabesh',
    exampleImage: './Aurabesh/Aurabesh-example.png',
    script: 'Aurebesh',
    foundry: 'Mike E. Web',
    foundryQuery: 'MikeEWeb',
    artistNote: '',
    description: 'The first Aurebesh font; small lowercase; basic nums; non-canon punctuation & symbols',
    downloadUrl: './Aurabesh/AURABESH.ttf',
    downloadType: '.TTF',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '1996',
    charactersImages: [],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
    additionalImages: []
  },
  {
    query: 'Auraboo',
    name: 'Auraboo',
    exampleImage: `./Auraboo/Auraboo-example.jpg`,
    script: '"Naboo Aurebesh"',
    scriptQuery: 'NabooAurebesh',
    foundry: 'Nick Tierce',
    foundryQuery: 'NickTierce',
    artistNote: 
      `Auraboo is based on a font seen briefly in Star Wars: Episode I, when R2-D2 tells Anakin to "turn the ship around and go back homie right awayl [sic]".
      Punctuation was based on a softened version of standard Aurebesh punctuation. <br />
      Missing letters (F, J, Q, V, X, and Z) were designed with input from AurekFonts. <br />
      Photoshop templates designed by AurekFonts: <a href="./Auraboo/PhotoshopTemplates.zip">PhotoshopTemplates.zip</a>`,
    description: `"Naboo Aurebesh" font based on Naboo Starfighter screen in The Phantom Menace; basic nums`,
    downloadUrl: './Auraboo/Auraboo.zip',
    downloadType: '.ZIP',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: [`./Auraboo/Auraboo-charset.png`],
    class: 'auraboo-demo auraboo-text',
    textSize: '2rem',
    pangram: pangrams.Homie,
    additionalImages: [
      `./Auraboo/Auraboo-example-2.png`, 
      `./Auraboo/Auraboo-example-3.png`,
    ]
  },
  {
    query: 'AurebeshAF',
    name: 'Aurebesh AF',
    exampleImage: `./AurebeshAF/AurebeshAF-example.png`,
    script: 'Aurebesh',
    scriptQuery: 'Aurebesh',
    foundry: 'AurekFonts',
    artistNote: ``,
    description: 'Clean, robust Aurebesh font with options for digraphs and tech numerals',
    downloadUrl: './AurebeshAF/AurebeshAF.zip',
    downloadType: '.ZIP',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: [`./AurebeshAF/AurebeshAF-example2.png`],
    additionalImages: [
      `./AurebeshAF/AurebeshAF-example3.png`, 
      `./AurebeshAF/AurebeshAF-example4.png`,
    ]
  },
  {
    query: 'AurebeshOcchino',
    name: 'Aurebesh (David Occhino)',
    exampleImage: undefined,
    script: 'Aurebesh',
    foundry: 'David Occhino Design',
    foundryQuery: 'DavidOcchino',
    artistNote: 'This version of the Aurebesh font has been featured in many publications, signs, posters and websites, including The Star Wars Insider Magazine, The Force.net website and Wookiepedia.',
    description: 'Aurebesh font used officially from time to time; ligature digraphs; basic nums',
    externalDownloadUrl: 'http://davidocchino.com/portfolio/typography/aurebesh.html',
    externalDownloadName: 'DavidOcchino.com',
    forLicensingName: 'DavidOcchino.com',
    forLicensingUrl: 'http://davidocchino.com/portfolio/typography/commercial-license-request-form.html',
    license: 'Single-User Non-Commercial License',
    licenseTag: 'Free NC',
    year: '1997, 2011',
    charactersImages: ['./AurebeshOcchino/AurebeshOcchino-charset.png'],
  },
  {
    query: 'AurebeshPixelSagas2000',
    name: 'Aurebesh (Pixel Sagas, 2000)',
    exampleImage: undefined,
    script: 'Aurebesh',
    foundry: 'Pixel Sagas',
    foundryQuery: 'PixelSagas',
    artistNote: '',
    description: 'Aurebesh font; capitals for digraphs; incorrect tech numerals',
    downloadUrl: './Aurebesh%20(Pixel%20Sagas%202000)/aurebesh-old.ttf',
    downloadType: '.TTF',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2000',
    charactersImages: [],
    class: 'AurebeshPixelSagas2000',
    textSize: '1rem',
    pangram: pangrams.JediWisdom,
  },
  {
    query: 'AurebeshPixelSagas',
    name: 'Aurebesh (Pixel Sagas)',
    exampleImage: undefined,
    script: 'Aurebesh',
    foundry: 'Pixel Sagas',
    foundryQuery: 'PixelSagas',
    artistNote: '',
    description: 'Popular Aurebesh font at a lighter weight; inverted capitals',
    downloadUrl: './Aurebesh%20(Pixel%20Sagas)/aurebesh.zip',
    downloadType: '.ZIP',
    license: 'Free for personal, non-commercial use.',
    licenseTag: 'Free NC',
    year: '2013',
    charactersImages: [],
    class: 'AurebeshPixelSagas',
    textSize: '1rem',
    pangram: pangrams.Podracing,
  },
  {
    query: 'AurebeshCantina',
    name: 'Aurebesh Cantina',
    exampleImage: undefined,
    script: 'Aurebesh',
    foundry: 'Pixel Sagas',
    foundryQuery: 'PixelSagas',
    artistNote: '',
    description: 'Narrow art-deco inspired Aurebesh; inverted capitals; 4 styles',
    downloadUrl: './AurebeshCantina/aurebesh_cantina.zip',
    downloadType: '.ZIP',
    license: 'Free for personal, non-commercial use.',
    licenseTag: 'Free NC',
    year: '2015',
    charactersImages: [],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'AurebeshCalligraphy',
    name: 'Aurebesh Calligraphy',
    exampleImage: './AurebeshCalligraphy/AurebeshCalligraphy-example.png',
    script: 'Aurebesh',
    foundry: 'Convallarias Art',
    foundryQuery: 'ConvallariasArt',
    artistNote: '"I didn’t find any sort of things like Aurebesh cursive, so decided to do one myself c:"',
    description: 'Brush-stroke calligraphic Aurebesh font',
    downloadUrl: './AurebeshCalligraphy/AurebeshCalligraphy-Regular.ttf',
    downloadType: '.TTF',
    license: 'This font is "Free for all personal and commercial use."',
    licenseTag: 'Free',
    year: '2018',
    charactersImages: ['./AurebeshCalligraphy/AurebeshCalligraphy-charset.png'],
    class: 'AurebeshCalligraphy',
    textSize: '1.5rem',
    pangram: pangrams.JediWisdom,
  },
  {
    query: 'AurebeshEnglish',
    name: 'Aurebesh English',
    exampleImage: './AurebeshEnglish/aurebesh-english-example.png',
    script: 'High Galactic Alphabet',
    scriptQuery: 'HighGalactic',
    foundry: 'Stormtrooper On Weekends',
    foundryQuery: 'StormtrooperOnWeekends',
    artistNote: undefined,
    description: `High Galactic font, based on signage at Galaxy's Edge; basic nums`,
    downloadUrl: './AurebeshEnglish/Aurebesh-English.ttf',
    downloadType: '.TTF',
    license: 'This font is Free for all personal and commercial use.',
    licenseTag: 'Free',
    year: '2019',
    charactersImages: ['./AurebeshEnglish/aurebesh-english-charset.png?raw=true'],
    class: 'aurebeshenglish-text aurebeshenglish-demo',
    textSize: '1.5rem',
    pangram: pangrams.BSO,
  },
  {
    query: 'AurebeshDroid',
    name: 'Aurebesh Droid',
    exampleImage: './Aurebesh%20Droid/aurebesh-droid-example.png',
    script: 'Droidobesh',
    foundry: 'Stormtrooper On Weekends',
    foundryQuery: 'StormtrooperOnWeekends',
    artistNote: '"This font is based on the droid version of the Aurebesh typeface used in Star Wars."',
    description: 'Basic Droidobesh font; tech nums',
    downloadUrl: './Aurebesh%20Droid/Aurebesh-Droid.ttf',
    downloadType: '.TTF',
    license: 'This font is Free for all personal and commercial use.',
    licenseTag: 'Free',
    year: '2019',
    charactersImages: ['./Aurebesh%20Droid/aurebesh-droid-charset.png?raw=true'],
    class: 'AurebeshDroid aurebeshenglish-demo',
    textSize: '2rem',
    pangram: pangrams.BSO,
  },
  {
    query: 'AurebeshLU',
    name: 'Aurebesh LU',
    exampleImage: './LucyUniverse/aurebesh-lu-example.png',
    script: 'Aurebesh',
    foundry: 'Lucy Universe',
    foundryQuery: 'LucyUniverse',
    artistNote: ``,
    description: `8-bit Aurebesh font`,
    downloadUrl: './LucyUniverse/AurebeshLU.otf',
    downloadType: '.OTF',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    seeAlso: 'Ur-Kittât LU',
    seeAlsoQuery: 'UrKittatLU',
    charactersImages: [],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'AurebeshNewRoman',
    name: 'Aurebesh New Roman',
    exampleImage: undefined,
    script: 'Aurebesh',
    foundry: 'David Occhino Design',
    foundryQuery: 'DavidOcchino',
    artistNote: '"AUREBESH NEW ROMAN is a serif-style typeface inspired by the Star Wars "Aurebesh" alphabet. Created to fill a need for a more legible Aurebesh typeface, Aurebesh New Roman can be used to set larger passages of text."',
    description: 'Serif Aurebesh font; basic nums; ligature digraphs; 6 styles',
    externalDownloadUrl: 'http://davidocchino.com/portfolio/typography/aurebesh-new-roman.html',
    externalDownloadName: 'DavidOcchino.com',
    forLicensingName: 'DavidOcchino.com',
    forLicensingUrl: 'http://davidocchino.com/portfolio/typography/commercial-license-request-form.html',
    license: 'Single-User Non-Commercial License',
    licenseTag: 'Free NC',
    year: '2014',
    charactersImages: ['./AurebeshNewRoman/Aurebesh-New-Roman-charset.png'],
  },
  {
    query: 'AurebeshOmaTres',
    name: 'Aurebesh Oma Tres',
    exampleImage: './AurebeshOmaTres/Aurebesh_OmaTres-example.png',
    script: 'Aurebesh',
    foundry: 'AurekFonts',
    artistNote: '',
    description: 'Aurebesh font based on the Star Wars logo and named for Oma Tres from The Rise of Skywalker',
    downloadUrl: './AurebeshOmaTres/Aurebesh_OmaTres_beta.otf',
    downloadType: '.OTF',
    license: 'This font is free for everyone, forever.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./AurebeshOmaTres/Aurebesh_OmaTres-charset.png'],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'AurebeshPixel',
    name: 'Aurebesh Pixel',
    exampleImage: './AurebeshPixel/Aurebesh-Pixel-example.png',
    script: 'Aurebesh',
    foundry: 'AurekFonts',
    artistNote: '',
    description: 'Pixel Aurebesh font; basic nums',
    downloadUrl: './AurebeshPixel/aurebesh-pixel.zip',
    downloadType: '.ZIP',
    license: 'This font is free for everyone, forever.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./AurebeshPixel/Aurebesh-Pixel-characters2.png'],
  },
  {
    query: 'AurebeshRed',
    name: 'Aurebesh Red',
    exampleImage: './AurebeshRed/AurebeshRed-TitleCard.png',
    script: 'Aurebesh',
    foundry: 'AurekFonts',
    artistNote: '',
    description: 'Monospace Aurebesh font',
    downloadUrl: './AurebeshRed/AurebeshRed.zip',
    downloadType: '.ZIP',
    license: 'This font is free for everyone, forever.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./AurebeshRed/AurebeshRed-charset.png'],
    class: undefined,
    textSize: '1.5rem',
    pangram: pangrams.JediWisdom,
  },
  {
    query: 'AurebeshRodian',
    name: 'Aurebesh Rodian',
    exampleImage: './Aurebesh%20Rodian/Aurebesh_Rodian-oblique-outline-example.png',
    script: 'Aurebesh',
    foundry: 'AurekFonts',
    artistNote: '',
    description: 'A curvy and friendly Aurebesh font; 4 styles',
    downloadUrl: './Aurebesh%20Rodian/Aurebesh_Rodian.zip',
    downloadType: '.ZIP',
    license: 'This font is free for everyone, forever.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./Aurebesh%20Rodian/Aurebesh_Rodian-charset.png'],
    class: 'AurebeshRodian',
    textSize: '1.5rem',
    pangram: pangrams.JediWisdom,
  },
  {
    query: 'AurebeshTycho',
    name: 'Aurebesh Tycho',
    exampleImage: undefined,
    script: 'Aurebesh',
    foundry: 'Tycho Ordo',
    foundryQuery: 'TychoOrdo',
    artistNote: '',
    description: 'A robust Aurebesh font; ligature-digraphs; optional inverted capitals and tech numerals',
    downloadUrl: './Aurebesh%20(Tycho%20Ordo)/AurebeshTycho.zip',
    downloadType: '.ZIP',
    license: 'Free for personal, non-commercial use.',
    licenseTag: 'Free NC',
    year: '2012, 2015, 2020',
    charactersImages: [],
    class: 'AurebeshTycho',
    textSize: '1.5rem',
    pangram: pangrams.BlackholeDigraphs,
  },
  {
    query: 'AurebeshSheev',
    name: 'Aurebesh Sheev',
    exampleImage:  `./AurebeshSheev/AurebeshSheev-example.png`,
    script: 'Aurebesh',
    foundry: 'AurekFonts',
    artistNote: '',
    description: 'Elegant hand-written Aurebesh font; still in beta; tech nums; 3 styles',
    downloadUrl: './AurebeshSheev/AurebeshSheev-BETA.zip',
    downloadType: '.ZIP',
    license: 'This font is free for everyone, forever.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./AurebeshSheev/AurebeshSheev-charset.png'],
    class: undefined,
    textSize: '1.5rem',
    pangram: pangrams.JediWisdom,
  },
  {
    query: 'AurebeshTypewriter',
    name: 'Aurebesh Typewriter',
    exampleImage:  `./AurebeshTypewriter/AurebeshTypewriter-example.png`,
    script: 'Aurebesh',
    foundry: 'AurekFonts',
    artistNote: '',
    description: 'Type-written Aurebesh font in two weights; digraphs mapped to symbol keys; basic nums',
    downloadUrl: './AurebeshTypewriter/AurebeshTypewriter.zip',
    downloadType: '.ZIP',
    license: 'This font is free for everyone, forever.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./AurebeshTypewriter/AurebeshTypewriter-charset.png'],
    class: undefined,
    textSize: '1.5rem',
    pangram: pangrams.JediWisdom,
  },
  {
    query: 'AurebeshVaporator',
    name: 'Aurebesh Vaporator',
    exampleImage:  `./AurebeshVaporator/AurebeshVaporator-example.png`,
    script: 'Aurebesh',
    foundry: 'AurekFonts',
    artistNote: '',
    description: 'Aurebesh title font; letters only',
    downloadUrl: './AurebeshVaporator/AurebeshVaporatorBETA.zip',
    downloadType: '.ZIP',
    license: 'This font is free for everyone, forever.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./AurebeshVaporator/AurebeshVaporator-charset.png'],
    class: undefined,
    textSize: '1.5rem',
    pangram: pangrams.JediWisdom,
  },
  {
    query: 'AurekBesh',
    name: 'Aurek-Besh',
    exampleImage: './AurekBesh/aureclip.jpg',
    script: 'Aurebesh',
    foundry: 'Boba Fonts',
    foundryQuery: 'BobaFonts',
    seeAlso: `Aurek-Besh Hand`, 
    seeAlsoQuery: `AurekBeshHand`,
    artistNote: 'Feel free to distribute the zip but remember to keep it intact and complete. This font is freeware.',
    description: `Standard Aurebesh font; tech nums; 2 styles`,
    downloadUrl: './AurekBesh/boba-fonts_aurek-besh.zip',
    downloadType: '.ZIP',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '1999',
    charactersImages: ['./AurekBesh/aurek-besh-charset.png'],
  },
  {
    query: 'AurekBeshHand',
    name: 'Aurek-Besh Hand',
    exampleImage: './AurekBeshHand/aurek-besh-hand-example.png',
    script: 'Aurebesh',
    foundry: 'Boba Fonts',
    foundryQuery: 'BobaFonts',
    seeAlso: `Aurek-Besh`, 
    seeAlsoQuery: `AurekBesh`, 
    artistNote: 'Feel free to distribute the zip but remember to keep it intact and complete. This font is freeware.',
    description: `Handwritten Aurebesh font; tech nums`,
    downloadUrl: './AurekBeshHand/boba-fonts_aurek-besh-hand.zip',
    downloadType: '.ZIP',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '1999',
    charactersImages: ['./AurekBeshHand/aurek-besh-hand-charset.png'],
    // class: 'AurekBeshHand', // TODO: Fix this?
    textSize: '2rem',
    pangram: pangrams.Podracing,
  },
  {
    query: 'AurekbeshMicalHandwritten',
    name: 'Aurekbesh Mical Handwritten',
    exampleImage: './AurekbeshMicalHandwritten/AurekbeshMicalHandwritten-example.png',
    script: 'Aurebesh',
    foundry: 'Kopanitsak',
    foundryQuery: 'Kopanitsak',
    artistNote: `"!!!Please don't offer this download anywhere else!!!"`,
    description: `Handwritten Aurebesh font; tech nums`,
    externalDownloadUrl: 'https://www.deviantart.com/kopanitsak/art/Aurekbesh-Mical-Handwritten-144424955',
    externalDownloadName: 'deviantart',
    license: 
      `<a 
        href="http://creativecommons.org/licenses/by-nc-nd/3.0/"
      >
        Creative Commons Attribution-Noncommercial-No Derivative Works 3.0 License
      </a>`,
    licenseTag: 'Free NC',
    year: '2009',
    charactersImages: ['./AurekbeshMicalHandwritten/AurekbeshMicalHandwritten-charset.png'],
    class: undefined, 
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'AureSerif',
    name: 'AureSerif',
    exampleImage: './AureSerif/AureSerif-example.png',
    script: 'Aurebesh',
    foundry: 'Legendsist',
    foundryQuery: 'Legendsist',
    artistNote: `Artist note:<br>外出自粛の時間を有効に使って、自分で初めてフォントを作ってみました。<br>スター・ウォーズの世界の文字「オーラベッシュ」のセリフ体です。<br>自分でも惚れ惚れするような出来栄えです`,
    description: `Serif Aurebesh font; A-z only`,
    license: `'Of course, it's license free.'`,
    licenseTag: 'Free',
    year: '2020',
    downloadUrl: './AureSerif/AureSerif.ttf',
    downloadType: '.TTF',
    charactersImages: ['./AureSerif/AureSerif-charset.png'],
    class: undefined, 
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'Boonta',
    name: `Boonta`,
    exampleImage: './banners/unknown-scripts.png',
    script: `Unidentified podracer-detail`,
    scriptQuery: `UnknownCanon`,
    foundry: 'Omega Design',
    foundryQuery: 'OmegaDesign',
    artistNote: ``,
    description: `Font based on unidentified markings on one or more podracers in The Phantom Menace`,
    downloadUrl: './Boonta/Boonta.zip',
    downloadType: '.ZIP',
    license: 'These fonts are "Charity-ware". (Meaning: if you like the fonts and plan to use them, please give a little more than usual to your favorite charities [...] or others the next time you have a chance.)',
    licenseTag: 'Free',
    year: '1999',
    charactersImages: [],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'ComicbeshSans',
    name: 'Comicbesh Sans AF',
    exampleImage: `./ComicbeshSans/ComicbeshSans-example.png`,
    script: 'Aurebesh',
    scriptQuery: 'Aurebesh',
    foundry: 'AurekFonts',
    artistNote: '',
    description: 'For writing very serious space-emails and what have you',
    downloadUrl: './ComicbeshSans/ComicbeshSansAF-BETA.zip',
    downloadType: '.ZIP',
    license: 'This font is free for everyone, forever.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./ComicbeshSans/ComicbeshSans-charset.png'],
    class: 'comicbeshsans-text comicbeshsans-demo',
    textSize: '3rem',
    pangram: pangrams.Original,
  },
  {
    query: 'ClyneseBend',
    name: 'Clynese Bend',
    exampleImage: `./ClyneseBend/Clynese_Bend-example.png`,
    script: 'Clynese / Corellian',
    scriptQuery: 'Clynese',
    foundry: 'AurekFonts',
    seeAlso: `Clynese Hand`, 
    seeAlsoQuery: `ClyneseHand`, 
    artistNote: '',
    description: 'Clynese variant for streetsigns; letter y is upside down; non-canon nums, based on Sabacc dice and cards',
    downloadUrl: './ClyneseBend/Clynese_Bend.otf',
    downloadType: '.OTF',
    license: 'This font is free for everyone, forever.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./ClyneseBend/Clynese_Bend-charset1.png'],
  },
  {
    query: 'ClyneseHand',
    name: 'Clynese Hand',
    exampleImage: `./ClyneseHand/Clynese_Hand-example.png`,
    script: 'Clynese / Corellian',
    scriptQuery: 'Clynese',
    foundry: 'AurekFonts',
    seeAlso: `Clynese Bend`, 
    seeAlsoQuery: `ClyneseBend`, 
    artistNote: '',
    description: 'Hand-written clynese font; case controls placement; non-canon nums, based on Sabacc dice and cards',
    downloadUrl: './ClyneseHand/Clynese_Hand.otf',
    downloadType: '.OTF',
    license: 'This font is free for everyone, forever.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./ClyneseHand/Clynese_Hand-charset.png'],
  },
  {
    query: 'Cyrillibesh',
    name: 'Cyrillibesh',
    exampleImage: `./Cyrillibesh/Cyrillibesh-example.png`,
    script: 'Aurebesh',
    scriptQuery: 'Aurebesh',
    foundry: 'AurekFonts',
    artistNote: '',
    description: 'Basic Aurebesh english, with additional non-canonical letters for writing Russian Aurebesh',
    downloadUrl: './Cyrillibesh/Cyrillibesh-BETA.otf',
    downloadType: '.OTF',
    license: 'This font is free for everyone, forever.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: [],
  },
  {
    query: 'DarkKatarn',
    name: 'Dark Katarn',
    exampleImage: './DarkKatarn/drkkatrn_sample.gif',
    script: 'Atrisian',
    foundry: 'erikstormtrooper',
    artistNote: `"ACCURACY OF THIS FONT There are only 12 "canon" letters in this alphabet, which appear in X-Wing. In my font, these letters are represented as: A, C, D, E, H, I, L, N, O, R, S, T. These 12 letters are the most frequent in English. I chose them so written passages would look as canon as possible. Most of the other letters in this font were inspired by barely-legible characters seen in Dark Forces. Numbers 1-6 are canon based on numbers seen in Dark Forces. I created numbers 7-9 and 0 in the same style."`,
    description: `<em>(Legends)</em> First fan font for Atrisian`,
    downloadUrl: './DarkKatarn/drkkatrn.zip',
    downloadType: '.ZIP',
    license: 'This font is freeware; it may be distributed freely, but PLEASE distribute all files included in the ZIP archive. This font is NOT to be sold  or used for financial gain. Help keep it free and available!',
    licenseTag: 'Free NC',
    year: '2003, 2004',
    charactersImages: [],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'DockingBay94',
    name: 'Docking Bay 94',
    exampleImage: `./DockingBay94/DockingBay94-example.png`,
    script: 'Aurebesh',
    foundry: 'AurekFonts',
    artistNote: '',
    description: 'Aurebesh font based on the docking bay signage at Mos Eisley Spaceport (Star Wars the Motion Picture, and The Mandalorian S1)',
    downloadUrl: './DockingBay94/DockingBay94-Display.otf',
    downloadType: '.OTF',
    license: 'This font is free for everyone, forever.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./DockingBay94/DockingBay94-charset.png'],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'DomabeshConsole',
    name: 'Domabesh Console',
    exampleImage: `./banners/domabesh-banner.png`,
    script: 'Domabesh',
    foundry: 'AurekFonts',
    artistNote: 'All the letters but J and V are canonical. The numbers and punctuation are noncanonical',
    description: 'Basic Domabesh font; digraphs mapped to symbol keys; tech nums',
    downloadUrl: './DomabeshConsole/DomabeshConsole.otf',
    downloadType: '.OTF',
    license: 'This font is free for everyone, forever.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./DomabeshConsole/DomabeshConsole-charset.png'],
    class: 'domabeshconsole-text domabeshconsole-demo',
    textSize: '3.5rem',
    pangram: pangrams.Jedha,
  },
  {
    query: 'Ewok',
    name: 'Ewok',
    exampleImage: undefined,
    script: 'Ewokese',
    foundry: 'Omega Design',
    foundryQuery: 'OmegaDesign',
    artistNote: '"Characters do *not* represent the keys they they are on.  Each character seems to stand for a word or situation. Ewok is written downward, not left to right."',
    description: '<em>Legends</em> Ewokese font based on symbols in the cartoon series.',
    downloadUrl: './Ewok/Ewok.zip',
    downloadType: '.ZIP',
    license: 'These fonts are "Charity-ware". (Meaning: if you like the fonts and plan to use them, please give a little more than usual to your favorite charities [...] or others the next time you have a chance.)',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: [],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'EngliBesh',
    name: 'Engli-Besh',
    exampleImage: `./EngliBesh/englbesh_sample.jpg`,
    script: '"Psuedobesh"',
    scriptQuery: 'Pseudobesh',
    foundry: 'erikstormtrooper',
    artistNote: '',
    description: `"Psuedobesh" font based on the "Imperial Code" font Galactic Basic`,
    seeAlso: 'Galactic Basic',
    seeAlsoQuery: 'GalacticBasic',
    downloadUrl: './EngliBesh/englbesh.zip',
    downloadType: '.ZIP',
    license: 'This font is freeware; it may be distributed freely, but PLEASE distribute all files included in the ZIP archive. This font is NOT to be sold  or used for financial gain. Help keep it free and available!',
    licenseTag: 'Free NC',
    year: '2002',
    charactersImages: ['./EngliBesh/EngliBesh-charset.png'],
    class: 'galacticbasic-demo englibesh-text',
    textSize: '2rem',
    pangram: pangrams.JazzyFox,
  },
  {
    query: 'Hellpoint',
    name: 'Hellpoint',
    exampleImage: undefined,
    script: '"Psuedobesh"',
    scriptQuery: 'Pseudobesh',
    foundry: 'Pixel Sagas',
    foundryQuery: 'PixelSagas',
    artistNote: '',
    description: `Although listed as a Transformers font, it is almost certainly based upon Engli-Besh`,
    seeAlso: 'Engli-Besh by erikstormtrooper',
    seeAlsoQuery: 'EngliBesh',
    downloadUrl: './Hellpoint/hellpoint.zip',
    downloadType: '.ZIP',
    license: 'Free for personal, non-commercial use.',
    licenseTag: 'Free NC',
    year: '2015',
    charactersImages: ['./Hellpoint/Hellpoint-charset.png'],
    class: 'galacticbasic-demo hellpoint-text',
    textSize: '2.5rem',
    pangram: pangrams.JazzyFox,
  },
  {
    query: 'ImperialCode',
    name: 'Imperial Code',
    exampleImage: undefined,
    script: '"Psuedobesh"',
    scriptQuery: 'Pseudobesh',
    foundry: 'Iconian Fonts',
    foundryQuery: 'IconianFonts',
    artistNote: '',
    description: `"Pseudobesh" font; in spite of its name, not an "Imperial Code" font`,
    downloadUrl: './ImperialCode/ImperialCode.zip',
    downloadType: '.ZIP',
    license: 'Free for personal, non-commercial use.',
    licenseTag: 'Free NC',
    forLicensingUrl: 'http://www.iconian.com/commercial.html',
    forLicensingName: 'Iconian.com',
    year: '2003',
    charactersImages: [],
    class: 'galacticbasic-demo imperialcode-text',
    textSize: '3rem',
    pangram: pangrams.JazzyFox,
  },
  {
    query: 'JabbaTheFont',
    name: 'JabbaTheFont',
    exampleImage: undefined,
    script: '"Psuedobesh"',
    scriptQuery: 'Pseudobesh',
    foundry: 'Michael Moss',
    foundryQuery: 'MichaelMoss',
    artistNote: '',
    description: `"Pseudobesh" font`,
    downloadUrl: './JabbaTheFont/JabbaTheFont.zip',
    downloadType: '.ZIP',
    license: '<a href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License.</a>',
    licenseTag: 'Free',
    year: '2018',
    charactersImages: [],
    class: 'galacticbasic-demo jabbathefont-text',
    textSize: '2rem',
    pangram: pangrams.JazzyFox,
  },
  {
    query: 'GalacticBasic',
    name: 'Galactic Basic',
    exampleImage: `./GalacticBasic/GalacticBasic-example.png`,
    script: '"Imperial Code"',
    scriptQuery: 'ImperialCode',
    foundry: 'erikstormtrooper',
    artistNote: '',
    description: `"Imperial Code" font based on designs by Joe Johnston for Return of the Jedi and Philip Metschan for Attack of the Clones`,
    seeAlso: 'Engli-Besh',
    seeAlsoQuery: 'EngliBesh',
    downloadUrl: './GalacticBasic/galactic_basic.zip',
    downloadType: '.ZIP',
    license: 'This font is freeware; it may be distributed freely, but PLEASE distribute all files included in the ZIP archive. This font is NOT to be sold  or used for financial gain. Help keep it free and available!',
    licenseTag: 'Free NC',
    year: '1996, 2002',
    charactersImages: ['./GalacticBasic/GalacticBasic-charset.png'],
    class: 'galacticbasic-demo galacticbasic-text',
    textSize: '2rem',
    pangram: pangrams.Tydirium,
  },
  {
    query: 'GeonosianPM',
    name: 'Geonosian PM',
    exampleImage: `./Geonosian%20PM/GeonosianPM-example.png`,
    script: 'Geonosian',
    foundry: 'AurekFonts',
    artistNote: '',
    description: `Geonosian font based on Philip Metschan's original design`,
    downloadUrl: './Geonosian%20PM/GeonosianPM.otf',
    downloadType: '.OTF',
    license: 'This font is free for everyone, forever.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./Geonosian%20PM/GeonosianPM-charset.png'],
    class: 'GeonosianPM',
    textSize: '2rem',
    pangram: pangrams.Podracing,
  },
  {
    query: 'Kitisakkullian',
    name: 'Kitisakkullian',
    exampleImage: './Kitisakkullian/Kitisakkullian-example.png',
    script: 'Kitisakkullian',
    foundry: 'AurekFonts',
    artistNote: ``,
    description: `Kitisakkullian font; all glyphs are canon; their mapping is arbitrary`,
    downloadUrl: './Kitisakkullian/Kitisakkullian.otf',
    downloadType: '.OTF',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./Kitisakkullian/Kitisakkullian-charset.png'],
    textSize: '2rem',
    pangram: pangrams.short,
  },
  {
    query: 'ImperialBroadcast87',
    name: 'Imperial Broadcast 87',
    exampleImage: './ImperialBroadcast87/ImperialBroadcast87-example.png',
    script: 'Unknown (Legends)',
    scriptQuery: 'UnknownLegends',
    foundry: 'AurekFonts',
    artistNote: `Based on the introduction of <a href="https://www.youtube.com/watch?v=zHzVjP9sH50">a 1987 broadcast of The Empire Strikes Back on NBC</a>`,
    description: `Based on a 1987 broadcast of The Empire Strikes Back`,
    downloadUrl: './ImperialBroadcast87/ImperialBroadcast87.otf',
    downloadType: '.OTF',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: [],
    textSize: '2rem',
  },
  {
    query: 'KCDAurebesh',
    name: 'Kyber Crystal Display Aurebesh',
    exampleImage: './Kyber%20Crystal%20Display/KCD-example.png',
    script: 'Aurebesh',
    foundry: 'AurekFonts',
    artistNote: ``,
    description: `For security consoles; includes Alphabet version`,
    seeAlso: `Kyber Crystal Display Alphabet`, 
    seeAlsoQuery: `KCDAlphabet`, 
    downloadUrl: './Kyber%20Crystal%20Display/KyberCrystalDisplay.zip',
    downloadType: '.ZIP',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./Kyber%20Crystal%20Display/KCD-Aurebesh-charset.png'],
    class: 'kcd-demo kcdaurebesh-text',
    textSize: '4rem',
    pangram: 'area secure',
  },
  {
    query: 'KCDAlphabet',
    name: 'Kyber Crystal Display Alphabet',
    exampleImage: './Kyber%20Crystal%20Display/KCD-example.png',
    script: 'HighGalactic',
    foundry: 'AurekFonts',
    artistNote: ``,
    description: `For security consoles; includes Aurebesh version`,
    seeAlso: `Kyber Crystal Display Aurebesh`, 
    seeAlsoQuery: `KCDAurebesh`, 
    downloadUrl: './Kyber%20Crystal%20Display/KyberCrystalDisplay.zip',
    downloadType: '.ZIP',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./Kyber%20Crystal%20Display/KCD-Alphabet-charset.png'],
    class: 'kcd-demo kcdalphabet-text',
    textSize: '4rem',
    pangram: 'area secure',
  },
  {
    query: 'Maulobesh',
    name: 'Maulobesh',
    exampleImage: './Maulobesh/Maulobesh-example-1.png',
    script: 'Aurebesh',
    foundry: 'AurekFonts',
    artistNote: ``,
    description: `A blackletter Aurebesh font; tech nums; basic punctuation`,
    downloadUrl: './Maulobesh/Maulobesh.otf',
    downloadType: '.OTF',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./Maulobesh/Maulobesh-charset.png'],
    class: 'Maulobesh',
    textSize: '2rem',
    pangram: pangrams.short,
  },
  {
    query: 'Mandalorian',
    name: 'Mandalorian',
    exampleImage: './Mandalorian/mandalorian_sample.gif',
    script: 'Mandalorian',
    foundry: 'erikstormtrooper',
    artistNote: ``,
    description: `Mandalorian font based on Philip Metschan's design seen in the Slave I's consoles in Attack of the Clones; a few letters off-canon; Mandalorian nums`,
    downloadUrl: './Mandalorian/mandalor.zip',
    downloadType: '.ZIP',
    license: 'This font is freeware; it may be distributed freely, but PLEASE distribute all files included in the ZIP archive. This font is NOT to be sold  or used for financial gain. Help keep it free and available!',
    licenseTag: 'Free NC',
    year: '2005, 2010',
    charactersImages: ['./Mandalorian/mandalorian-charset.png'],
    class: 'mandalorian-demo mandalorian-text',
    textSize: '4rem',
    pangram: 'this is the way',
  },
  {
    query: 'AlbansBane',
    name: `Mando Alban's Bane`,
    exampleImage: './MandoAlbansBane/Mando_AlbansBane-example.png',
    script: `Mandalorian`,
    foundry: 'AurekFonts',
    artistNote: ``,
    description: `Mandalorian font based on the Visual Encyclopedia; missing punctuation; Mandalorian nums`,
    downloadUrl: './MandoAlbansBane/Mando_AlbansBaneBETA.otf',
    downloadType: '.OTF',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./MandoAlbansBane/Mando_AlbansBane-charset.png'],
    class: 'mandoalbansbane-demo mandoalbansbane-text',
    textSize: '5rem',
    pangram: 'this is the way',
  },
  {
    query: 'MetalRebel',
    name: 'Metal Rebel',
    exampleImage: './MetalRebel/metalrebel_sample.gif',
    script: 'UnknownCanon',
    foundry: 'erikstormtrooper',
    artistNote: `"FONT INFORMATION This Star Wars font was inspired by writing on two Y-Wing helmets worn by Grey Squadron in Return of the Jedi. This font includes all English letters, numbers, and common punctuation marks (basically, all the stuff displayed on the keyboard). Uppercase and lowercase  letters are identical except that uppercase letters have a slightly taller spine. Also, kerning has been enabled for this font. <br /> ACCURACY OF THIS FONT There are only 11 "canon" letters in this alphabet, taken from two Y-Wing helmets in ROJ. These 11 canon letters are represented as:  A, D, E, H, I, L, N, O, R, S, T. These are the 11 most frequently  used letters in English. I chose them so that written passages  would look as canon as possible. I modeled the other letters in  this font to match the "square-ness" of the canon letters, which  bear a faint resemblance to a sans-serifed Hebrew.  The concept for numbers comes from one of the markings on the side of Grey Leader's helmet. Since I had a kind of Hebrew theme going,  I also used that as an inspiration for the numbers. Modern Hebrew  commonly uses arabic numerals (1-9), but in ancient Hebrew, letters  of the alphabet got double-duty as numbers. So, I based numbers  1-9 (and 0) on the first 10 letters of this font."`,
    description: `Unidentified script font based upon Grey Leader's helmet in Return of the Jedi`,
    downloadUrl: './MetalRebel/metlrebl.zip',
    downloadType: '.ZIP',
    license: 'This font is freeware; it may be distributed freely, but PLEASE distribute all files included in the ZIP archive. This font is NOT to be sold  or used for financial gain. Help keep it free and available!',
    licenseTag: 'Free NC',
    year: '2004',
    charactersImages: ['./MetalRebel/Metal-Rebel-charset.png'],
    additionalImages: ['./MetalRebel/Metal-Rebel-example.png'],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'Naboo',
    name: `Naboo`,
    exampleImage: undefined,
    script: `Naboo Futhark`,
    scriptQuery: `NabooFuthark`,
    foundry: 'Omega Design',
    foundryQuery: 'OmegaDesign',
    artistNote: ``,
    description: `Futhark font based on the markings on Naboo Starfighters in the Phantom Menace`,
    downloadUrl: './Naboo/Naboo.zip',
    downloadType: '.ZIP',
    license: 'These fonts are "Charity-ware". (Meaning: if you like the fonts and plan to use them, please give a little more than usual to your favorite charities [...] or others the next time you have a chance.)',
    licenseTag: 'Free',
    year: '1999',
    charactersImages: [],
    class: 'naboo-demo naboo-text',
    textSize: '4rem',
    pangram: pangrams.short,
  },
  {
    query: 'NalHuttese',
    name: `Nal-Huttese`,
    exampleImage: undefined,
    script: `Outer Rim Basic`,
    scriptQuery: `OuterRim`,
    foundry: 'Omega Design',
    foundryQuery: 'OmegaDesign',
    artistNote: `The most common version of this font you will find was made in 1999 and contains numerals 1-3 and the letters A-T. Harder to find is a 2000 version with 0-9 and A-Z. This download contains both, with the 1999 one marked as Nal-Huttese-99. It is included only for historical purposes, don't install it.`,
    description: `Outer Rim Basic font misidentified as Huttese, based on glyphs seen in The Phantom Menace; 2 versions included`,
    downloadUrl: './NalHuttese/nal-hutt.zip',
    downloadType: '.ZIP',
    license: 'These fonts are "Charity-ware". (Meaning: if you like the fonts and plan to use them, please give a little more than usual to your favorite charities [...] or others the next time you have a chance.)',
    licenseTag: 'Free',
    year: '1999, 2000',
    charactersImages: [],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'NewAurabesh',
    name: `New Aurabesh`,
    exampleImage: './NewAurabesh/NewAurabesh-example.png',
    script: `Aurebesh`,
    scriptQuery: `Aurebesh`,
    foundry: 'Peter Schuster',
    foundryQuery: 'PeterSchuster',
    artistNote: `About: <a href="https://www.ko-fi.com/post/New-Aurabesh-A-Casual-Interview-with-Peter-Schu-Q5Q41QAX6">Aurabesh New: A Casual Interview with Peter Schuster</a>`,
    description: `Standard Aurebesh font; small tech nums`,
    downloadUrl: './NewAurabesh/newaure.zip',
    downloadType: '.ZIP',
    license: 'Free for all personal and commercial uses',
    licenseTag: 'Free',
    year: '1998',
    charactersImages: [],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'NewFuthork',
    name: 'New Futhork',
    exampleImage: './NewFuthork/newfuthork_sample.gif',
    script: 'NabooFuthork',
    foundry: 'erikstormtrooper',
    artistNote: `"FONT INFORMATION This font is a canon version of the Star Wars alphabet known as "Naboo Futhork". The details of this font were taken from the passcodes screen in the 2000 game "Battle For Naboo". "`,
    description: `Naboo Futhork font; no nums`,
    downloadUrl: './NewFuthork/new_futhork.zip',
    downloadType: '.ZIP',
    license: 'This font is freeware; it may be distributed freely, but PLEASE distribute all files included in the ZIP archive. This font is NOT to be sold  or used for financial gain. Help keep it free and available!',
    licenseTag: 'Free NC',
    year: '2006, 2008',
    charactersImages: ['./NewFuthork/newfuthork_table.jpg'],
    class: 'newfuthork-demo newfuthork-text',
    textSize: '2rem',
    pangram: pangrams.JarJarFez,
  },
  {
    query: 'Nirvanabesh',
    name: 'Nirvanabesh',
    exampleImage: './Nirvanabesh/Nirvanabesh-example.png',
    script: 'Aurebesh',
    foundry: 'Vamplify',
    artistNote: `(with kerning by <a href="${pathname}?foundry=AurekFonts">AurekFonts</a>).`,
    description: `A serif Aurebesh font based on the band Nirvana's logotype; no nums; no symbols`,
    downloadUrl: './Nirvanabesh/Nirvanabesh.otf',
    downloadType: '.OTF',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./Nirvanabesh/Nirvanabesh-charset.png'],
    class: 'Nirvanabesh',
    textSize: '5rem',
    pangram: pangrams.short,
  },
  {
    query: 'OldTongue',
    name: 'Old Tongue',
    exampleImage: undefined,
    script: '"The Old Tongue" / Ur-Kittât',
    scriptQuery: 'OldTongue',
    foundry: 'Cake',
    artistNote: ``,
    description: `Slightly pixelated Old Tongue font; probably the first fan-made Old Tongue font`,
    downloadUrl: './FontsByCake/old-tongue.ttf',
    downloadType: '.TTF',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2019',
    charactersImages: [],
    class: undefined,
    textSize: '2rem',
    pangram: pangrams.short,
  },
  {
    query: 'OldTongueYavin',
    name: 'Old Tongue Yavin',
    exampleImage: './Old%20Tongue%20Yavin/OldTongue_Yavin-example.png',
    script: '"The Old Tongue" / Ur-Kittât',
    scriptQuery: 'OldTongue',
    foundry: 'AurekFonts',
    artistNote: ``,
    description: `Basic Old Tongue font; non-canon punctuation; non-canon tech nums; letter U is a little off`,
    downloadUrl: './Old%20Tongue%20Yavin/OldTongue_Yavin.otf',
    downloadType: '.OTF',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./Old%20Tongue%20Yavin/OldTongue_Yavin-charset.png'],
    class: 'OldTongueYavin',
    textSize: '3rem',
    pangram: pangrams.short,
  },
  {
    query: 'OuterRimAF',
    name: 'Outer Rim AF',
    exampleImage: './OuterRimAF/OuterRimAF-example.png',
    script: 'Outer Rim Basic',
    scriptQuery: 'OuterRim',
    foundry: 'AurekFonts',
    artistNote: ``,
    description: `Outer Rim Basic font, featuring full canonical alphabet and numerals`,
    downloadUrl: './OuterRimAF/OuterRimAF-Regular.otf',
    downloadType: '.OTF',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./OuterRimAF/OuterRimAF-charset.png'],
    class: 'OuterRimAF',
    textSize: '3rem',
    pangram: pangrams.short,
  },
  {
    query: 'PrimeJedi',
    name: 'Prime Jedi',
    exampleImage: './PrimeJedi/primejedi-example.png',
    script:  `"The Old Tongue" / Ur-Kittât`,
    scriptQuery: 'OldTongue',
    foundry: 'Meagan Bethel',
    foundryQuery: 'MeaganBethel',
    artistNote: ``,
    description: `Old Tongue font based on merchandise sold at Galacxy's Edge`,
    downloadUrl: './PrimeJedi/PrimeJedi.otf',
    downloadType: '.OTF',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./PrimeJedi/primejedi-charset.png'],
    class: undefined,
    textSize: '3rem',
    pangram: pangrams.short,
  },
  {
    query: 'Protobesh',
    name: 'Protobesh',
    exampleImage: './Protobesh/protobesh-example.png',
    script: 'Protobesh / Coremaic',
    scriptQuery: 'Protobesh',
    foundry: 'AurekFonts',
    artistNote: `"It was a long process to decode this script from the artwork for The Rise of Skywalker, but it holds up to scrutiny."`,
    description: `Protobesh font based on inscriptions in the Sacred Jedi Texts; non-canon nums; 2 styles`,
    downloadUrl: './Protobesh/Protobesh.zip',
    downloadType: '.ZIP',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./Protobesh/ProtobeshCoremaic-charset.png', './Protobesh/ProtobeshSquare-charset.png'],
    class: 'ProtobeshCoremaic',
    textSize: '3rem',
    pangram: pangrams.short,
  },
  {
    query: 'SaculBasic',
    name: 'Sacul Basic',
    exampleImage: './Sacul/SaculBasic-example.jpg',
    script: 'Aurebesh',
    scriptQuery: 'Aurebesh',
    foundry: 'Louie Mantia, Jr.',
    foundryQuery: 'LouieMantia',
    seeAlso: 'Sacul High Alphabet',
    seeAlsoQuery: 'SaculHighAlphabet',
    artistNote: `"This type is inspired by the designs seen in Star Wars. It isn't a replica of type seen in the films. Instead, it's a reinterpretation of existing characters to be a more legible, cohesive alphabet. Included is a Latin alphabet version as well, inspired by type seen in the Tokyo Disneyland Star Tours queue."`,
    description: `Aurebesh font redesined for clarity and balance; basic nums; comes with High Galactic version`,
    externalDownloadUrl: 'https://gumroad.com/l/sacul',
    externalDownloadName: `Louie Mantia's gumroad`,
    license: 'The font is only for personal, non-commercial use. If you wish to use this font commercially, you must first purchase a commercial license.',
    licenseTag: 'Lic Req',
    year: '2017',
    charactersImages: ['./Sacul/SaculBasic-charset.jpg'],
    additionalImages: ['./AurekFontsBanner.png'],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'SaculHighAlphabet',
    name: 'Sacul High Alphabet',
    exampleImage: './Sacul/SaculHighAlphabet-example.jpg',
    script: 'High Galactic Alphabet',
    scriptQuery: 'HighGalactic',
    foundry: 'Louie Mantia, Jr.',
    foundryQuery: 'LouieMantia',
    seeAlso: 'Sacul Basic',
    seeAlsoQuery: 'SaculBasic',
    artistNote: `"Inspired by type seen in the Tokyo Disneyland Star Tours queue."`,
    description: `High Galactic font inspired by text in the Tokyo Disneyland Star Tours queue; comes with Aurebesh version`,
    externalDownloadUrl: 'https://gumroad.com/l/sacul',
    externalDownloadName: `Louie Mantia's gumroad`,
    license: 'The font is only for personal, non-commercial use. If you wish to use this font commercially, you must first purchase a commercial license.',
    licenseTag: 'Lic Req',
    year: '2017',
    charactersImages: ['./Sacul/SaculHighAlphabet-charset.jpg'],
    additionalImages: [],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'SFoil',
    name: 'S-Foil',
    exampleImage: './SFoil/sfoil-example.png',
    script: 'Unidentified X-wing/Incom script',
    scriptQuery: 'UnknownCanon',
    foundry: 'AurekFonts',
    foundryQuery: 'AurekFonts',
    seeAlso: 'Almost There',
    seeAlsoQuery: 'AlmostThere',
    description: `Unknown script seen on Luke's X-wing console in Ep V and VI as well as various Rebel and Resistance screens in Ep VIII, Ep IX, and <em>Rogue One</em>`,
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    downloadUrl: './SFoil/SFoil-Regular.otf',
    downloadType: '.OTF',
    charactersImages: ['./SFoil/sfoil-charset-alpha.png', './SFoil/sfoil-charset-nums.png'],
    additionalImages: [],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'SithAF',
    name: 'Sith AF (beta)',
    exampleImage: './SithAF/SithAF-example-darth.png',
    script: 'Kittât',
    scriptQuery: 'Kittat',
    foundry: 'AurekFonts',
    foundryQuery: 'AurekFonts',
    artistNote:  `Â and Û may be written as "A^" and "U^" respectively.`,
    description: `Sith Kittât font; contains all 311 character combinations as ligatures; backwards compatible with most romanized Kittât`,
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    downloadUrl: './SithAF/SithAF-BETA.otf',
    downloadType: '.OTF (beta)',
    charactersImages: ['./SithAF/SithAF-charset.png'],
    additionalImages: ['./SithAF/SithAF-example-poster.png'],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'SithProphecy',
    name: 'Sith Prophecy',
    exampleImage: './SithProphecy/sithprophecy_sample.gif',
    script: 'Unidentified script',
    scriptQuery: 'UnknownCanon',
    foundry: 'erikstormtrooper',
    artistNote: ``,
    description: `Font based on the unidentified writing on every known version of Darth Vader's chestbox`,
    downloadUrl: './SithProphecy/sthproph.zip',
    downloadType: '.ZIP',
    license: 'This font is freeware; it may be distributed freely, but PLEASE distribute all files included in the ZIP archive. This font is NOT to be sold  or used for financial gain. Help keep it free and available!',
    licenseTag: 'Free NC',
    year: '2004, 2006',
    charactersImages: ['./SithProphecy/sithprophecy_table.jpg', './SithProphecy/sithprophecy_guide.gif'],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'SkyLuke',
    name: 'Sky Luke',
    exampleImage: './SkyLuke/skyluke-example.png',
    script: 'High Galactic',
    scriptQuery: 'HighGalactic',
    foundry: 'AurekFonts',
    artistNote: undefined,
    description: `Based upon Luke Skywalker's signature in the book "The Jedi Path" by Daniel Wallace.`,
    downloadUrl: './SkyLuke/SkyLuke.zip',
    downloadType: '.ZIP',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: [],
    additionalImages: [
      './SkyLuke/skyluke-example-2.png',
      './SkyLuke/skyluke-example-3.png',
      './SkyLuke/skyluke-example-4.png',
      './SkyLuke/skyluke-example-5.png',
      './SkyLuke/skyluke-example-0.png',
    ],
    class: 'SkyLuke',
    textSize: '3rem',
    pangram: pangrams.short,
  },
  {
    query: 'Snubfighter',
    name: 'Snubfighter',
    exampleImage: undefined,
    script: 'High Galactic Alphabet',
    scriptQuery: 'HighGalactic',
    foundry: 'Iconian Fonts',
    foundryQuery: 'IconianFonts',
    artistNote: ``,
    description: `High Galactic version of Metal Rebel; designed by Iconian Fonts with direction from erikstormtrooper`,
    seeAlso: 'Metal Rebel by erikstormtrooper',
    seeAlsoQuery: 'MetalRebel',
    downloadUrl: './Snubfighter/snubfighter.zip',
    downloadType: '.ZIP',
    license: 'Free for personal, non-commercial use.',
    licenseTag: 'Free NC',
    forLicensingUrl: 'http://www.iconian.com/commercial.html',
    forLicensingName: 'Iconian.com',
    year: '2009',
    charactersImages: [],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'SWyavin4',
    name: 'SWyavin4',
    exampleImage: undefined,
    script: 'Quasi-Old Tongue',
    scriptQuery: 'OldTongue',
    foundry: `\"Tommy\" of Escondido`,
    foundryQuery: `TommyofEscondido`,
    artistNote: `"This is the Yavin 4 font, based on the Alien lettering used in THE ILLUSTRATED STARWARS UNIVERSE book on the Yavin 4 temple walls.  This was an illustration of the movie: StarWars: A New Hope. The jungle temple on the Yavin 4 moon was  the final base from which the rebels attacked the first Death Star.  The script is also known as Teresian, according to the StarWars comic books.  It seems to  be written horizontal, but it is uncertain if it is right-to-left or vice-versa."`,
    description: `Non-canon glyphs, based on the same source material as the "Old Tongue" proper`,
    downloadUrl: './SWyavin4/swyavin4.zip',
    downloadType: '.ZIP',
    license: 'This is charity-ware - if you find it at all worthwhile, please give more to charity',
    licenseTag: 'Free',
    year: '1997',
    charactersImages: [],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'TradeHuttese',
    name: 'Trade Huttese',
    exampleImage: undefined,
    script: `"Jabba's Alphabet" <em>(Legends)</em>`,
    scriptQuery: 'JabbasAlphabet',
    foundry: `\"Tommy\" of Escondido`,
    foundryQuery: `TommyofEscondido`,
    artistNote: ``,
    description: `<em>Legends</em> font based on "Jabba's Alphabet" from 1997 Pizza Hut boxes`,
    downloadUrl: './TradeHuttese/huttese.zip',
    downloadType: '.ZIP',
    license: `This is charity-ware - if you find it at all worthwhile, please give more to charity`,
    licenseTag: 'Free',
    year: '1999',
    charactersImages: [],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'TradeFederation',
    name: 'Trade Federation',
    exampleImage: undefined,
    script: `Trade Federation Basic`,
    scriptQuery: 'TradeFederation',
    foundry: `Peter Schuster`,
    foundryQuery: `PeterSchuster`,
    artistNote: ``,
    description: `Trade Federation font, based on pre-release information for The Phantom Menace from StarWars.com; A-Z, 1-6; Trade Federation nums`,
    downloadUrl: './TradeFederation/tradefederation.zip',
    downloadType: '.ZIP',
    license: `Free Personal Non-Commercial`,
    licenseTag: 'Free NC',
    year: '1998',
    charactersImages: [],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'TFGunray',
    name: 'TF Gunray',
    exampleImage: './TFGunray/tfgunray-example.png',
    script: `Trade Federation Basic`,
    scriptQuery: 'TradeFederation',
    foundry: 'AurekFonts',
    artistNote: ``,
    description: `Trade Federation font, based on the Visual Encyclopedia; complete alphabet and nums; Trade Federation nums`,
    downloadUrl: './TFGunray/TFGunray-Bold.otf',
    downloadType: '.OTF',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./TFGunray/tfgunray-charset.png'],
    class: 'tfgunray-text tfgunray-demo',
    textSize: '3rem',
    pangram: `1138 Roger Roger`,
  },
  {
    query: 'UbeseBoushh',
    name: 'Ubese Boushh',
    exampleImage: './UbeseBoushh/Ubese_Boushh_BETA-example.png',
    script: `\'Ubese\' [unidentified script from Boushh's costume]`,
    scriptQuery: 'Ubese',
    foundry: 'AurekFonts',
    artistNote: `There are only enough letters to fill out the phonology of Ubese, as heard in RotJ.<br><br>Check out the <a href="http://AurekFonts.github.io/guide-ubese.html">Guide to Speaking Ubese</a> to learn how to speak Ubese.`,
    description: `"Ubese" font based on Boushh's clothing; limited glyphs; some non-canon glyphs; no nums`,
    downloadUrl: './UbeseBoushh/ubese-boushh-beta.zip',
    downloadType: '.ZIP',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./UbeseBoushh/Ubese_Boushh_BETA-charaset.png'],
    class: 'ubese-boushh-text ubese-boushh-demo',
    textSize: '3rem',
    pangram: `1111 shei 1138`,
  },
  {
    query: 'UrKittat',
    name: 'Ur Kittat',
    exampleImage: './UrKittat/UrKittat-example.png',
    script: `"The Old Tongue" / Ur-Kittât`,
    scriptQuery: 'OldTongue',
    foundry: 'Luke Daley',
    foundryQuery: 'LukeDaley',
    artistNote: `I created This typeface to contribute to the community and legacy of Star Wars fans!
    <br><br>I needed the Ur-Kittat for a design project and realised there was no font file for the ancient runic language of the sith, used on Oshi's Dagger as well as many places throughout the Star Wars Universe
    <br><br>the Sith Eternal Symbol can be called with '!' (I've also included my logo on '*')`,
    description: `"Old Tongue" font based on Galaxy's Edge merchandise; no nums; Sith Eternal sigil as exclamation mark`,
    downloadUrl: 'UrKittat/ur_kittat.zip',
    downloadType: '.ZIP',
    license: `CC BY-ND: This license allows reusers to copy and distribute the material in any medium or format in unadapted form only,
    and only so long as attribution is given to the creator.
    The license allows for commercial use.`,
    forLicensingName: 'creativecommons.org/licenses/by-nd/4.0/',
    forLicensingUrl: 'https://creativecommons.org/licenses/by-nd/4.0/',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./UrKittat/UrKittat-charset.png'],
    class: undefined,
    textSize: '3rem',
    pangram: `1111 shei 1138`,
  },
  {
    query: 'UrKittatLU',
    name: 'Ur-Kittat LU',
    exampleImage: './LucyUniverse/urkittat-lu-example.png',
    script: 'Ur-Kittât / "Old Tongue"',
    scriptQuery: 'OldTongue',
    foundry: 'Lucy Universe',
    foundryQuery: 'LucyUniverse',
    artistNote: ``,
    description: `8-bit Ur-Kittat font`,
    downloadUrl: './LucyUniverse/UrKittatLU.otf',
    downloadType: '.OTF',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    seeAlso: 'Aurebesh LU',
    seeAlsoQuery: 'AurebeshLU',
    charactersImages: [],
    class: undefined,
    textSize: undefined,
    pangram: undefined,
  },
  {
    query: 'Veers',
    name: 'Veers Numeric',
    script: 'Numeric',
    exampleImage: './VeersNumeric/VeersNumeric-example.png',
    foundry: 'AurekFonts',
    artistNote: '',
    description: 'Numeric font based on the AT-AT periscope seen in <em>Empire Strikes Back</em>',
    downloadUrl: './VeersNumeric/VeersNumeric.otf',
    downloadType: '.OTF',
    license: 'Free for all personal and commercial uses.',
    licenseTag: 'Free',
    year: '2020',
    charactersImages: ['./VeersNumeric/VeersNumeric-charset.png'],
  },
]